import {calendarHTML,calendarDraft,calendarBlocks,calendarConflicts,bindCalendarGestures,clockMinutes,minuteClock,PIXELS_PER_MINUTE} from './calendar.js?v=11';
import {rhythmInsights} from './insights.js?v=11';
import {planInstructions,chatSummary,agendaContext,allForChat} from './planning.js?v=11';
import {bindTaskSwipes} from './task-swipe.js?v=13';
import {config} from './config.js';
import {passwordError,magicLinkToken,notificationSupport} from './access.js';
import {CLOSED,CATEGORIES,STATUS,escapeHtml as esc,dateKey,addDays,madridTime,timeLabel,dayLabel,duration,formatDuration,goalDuration,actualDuration,taskDay,organizerItems,organizerNoCooking,habits,currentTask,parsePlan,summaryText,WEEKDAYS,repeatDays,repeatLabel,recurrenceFor} from './domain.js?v=11';
const paths={home:'<path d="M3 10l9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18m-12 5h2m4 0h2"/>',plan:'<path d="M12 3v18M3 12h18"/>',chart:'<path d="M4 20h16M6 16V9m6 7V4m6 12v-5"/>',settings:'<path d="M12 3v3m0 12v3M3 12h3m12 0h3M5.6 5.6l2.1 2.1m8.6 8.6 2.1 2.1m0-12.8-2.1 2.1m-8.6 8.6-2.1 2.1"/><circle cx="12" cy="12" r="5"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',check:'<path d="m5 12 4 4L19 6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',play:'<path d="m8 4 12 8-12 8z"/>',edit:'<path d="m16 3 5 5-13 13H3v-5zM14 5l5 5"/>',back:'<path d="m14 6-6 6 6 6"/>',next:'<path d="m10 6 6 6-6 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',logout:'<path d="M9 3H3v18h6m6-16 7 7-7 7m-8-7h15"/>',spark:'<path d="m12 3 2.7 6.3L21 12l-6.3 2.7L12 21l-2.7-6.3L3 12l6.3-2.7z"/>'};
paths.trash='<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>';
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.clock}</svg>`;
const nav=[['today','home','Mi día'],['planning','calendar','Preparar mañana'],['balance','chart','Mi balance'],['settings','settings','Ajustes']];
const state={user:null,tasks:[],date:dateKey(),view:'today',filter:'all',dayView:'calendar',calendarZoom:'large',loading:true,busy:false,notifications:false,health:null,error:null};
let db,serviceWorker,refreshTimer,clockTimer,installPrompt;
const $=id=>document.getElementById(id);
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');const feedback=$('modal-feedback');if($('modal').open&&feedback){feedback.textContent=message;feedback.hidden=false;feedback.scrollIntoView({block:'nearest'});}clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),8000);}
const btn=(action,text,ic='',classes='',attrs='')=>`<button class="btn ${classes}" data-action="${action}" ${attrs}>${ic?icon(ic):''}${text}</button>`;
function modal(html){$('modal-body').innerHTML='<div id="modal-feedback" class="modal-feedback" role="alert" hidden></div>'+html;$('modal').showModal();}
const modalHeader=title=>`<div class="modal-header"><h2>${esc(title)}</h2>${btn('close-modal','<span class="sr-only">Cerrar</span>','close','icon-only','aria-label="Cerrar"')}</div>`;
function closeModal(){if($('modal').open)$('modal').close();}
function errorMessage(error){const msg=error?.message||String(error);if(/Invalid login credentials/.test(msg))return 'El correo o la contraseña no coinciden. Revisa tus datos.';if(error?.code==='over_email_send_rate_limit'||/email.*rate limit|rate limit.*email/i.test(msg))return 'Has alcanzado el límite de correos. Si ya tienes sesión en Safari, crea tu contraseña en Ajustes y entra con ella. También puedes pegar un enlace vigente que ya tengas.';if(/rate limit|too many/i.test(msg))return 'Hay demasiados intentos. Espera antes de volver a intentarlo.';if(/reauthentication/i.test(error?.code||msg))return 'Para cambiar la contraseña necesitas una sesión reciente. Vuelve a entrar y repite el cambio.';if(/fetch|network/i.test(msg))return 'No se pudo conectar. Comprueba Internet y vuelve a intentarlo.';if(/not authorized|forbidden|owner/i.test(msg))return 'Esta cuenta no tiene acceso a tu agenda personal.';return msg;}
let loginMode='password';
function renderLogin(mode=loginMode){
  loginMode=mode;
  const withPassword=mode==='password';
  $('app').innerHTML=`<main class="login"><section class="login-story"><div><div class="brand"><span class="brand-icon">r.</span>ritmo</div><h1>Un día con intención.<br><span>Una tarea a la vez.</span></h1><p>Un lugar para ordenar tu día, hacer espacio para lo que importa y volver a empezar cuando haga falta.</p><div class="login-feature"><span>${icon('calendar')}Tu agenda</span><span>${icon('bell')}Tus recordatorios</span><span>${icon('check')}Tu progreso</span></div></div><div class="login-story-footer">Tu espacio personal. Sin ruido.</div></section><section class="login-form"><div><div class="eyebrow">Bienvenida a tu espacio</div><h2>Vamos a por tu día</h2><p class="intro">Entra con tu cuenta personal para abrir tu agenda.</p><div class="segmented" role="group" aria-label="Forma de acceso"><button class="${withPassword?'active':''}" data-action="login-mode" data-mode="password" aria-pressed="${withPassword}">Con contraseña</button><button class="${!withPassword?'active':''}" data-action="login-mode" data-mode="link" aria-pressed="${!withPassword}">Con enlace</button></div><form id="login-form"><label for="email">Correo electrónico</label><input id="email" name="email" type="email" autocomplete="username" required placeholder="Tu correo">${withPassword?'<label for="login-password">Contraseña</label><input id="login-password" name="password" type="password" autocomplete="current-password" required placeholder="Tu contraseña">':'<label for="login-link">Enlace de tu correo</label><input id="login-link" name="link" type="url" autocomplete="off" required placeholder="Pega el enlace de acceso"><p class="hint">Mantén pulsado «Sign in» en el correo, copia su enlace y pégalo aquí. Puedes usar un enlace que ya tengas sin pedir otro.</p>'}${btn('login',withPassword?'Entrar a mi agenda':'Entrar con este enlace','','primary','type="submit"')}<p id="login-error" class="form-error" role="alert"></p></form>${withPassword?'<p class="hint">¿Aún no tienes contraseña? En Safari, donde ya iniciaste sesión, abre Ajustes → Crear o cambiar contraseña. Después podrás entrar aquí sin pedir correos.</p>':btn('request-link','Recibir enlace por correo','copy','subtle')+'<p class="hint">El correo tiene un límite de envíos. Si ya creaste una contraseña, usa «Con contraseña». Si la olvidaste, entra con un enlace y cámbiala en Ajustes.</p>'}<div class="divider"></div><p class="hint">Tu agenda solo admite tu cuenta autorizada. La sesión se mantiene en este dispositivo.</p></div></section></main>`;
  $('login-form').onsubmit=async e=>{
    e.preventDefault();if(state.busy)return;state.busy=true;const b=e.submitter;b.disabled=true;$('login-error').textContent='';
    try{
      const email=$('email').value.trim();
      const result=withPassword?await db.auth.signInWithPassword({email,password:$('login-password').value}):await db.auth.verifyOtp({token_hash:magicLinkToken($('login-link').value,config.supabaseUrl),type:'magiclink'});
      if(result.error)throw result.error;
      if(withPassword&&$('login-password'))$('login-password').value='';
    }catch(error){if($('login-error'))$('login-error').textContent=errorMessage(error);}
    finally{state.busy=false;if(b.isConnected)b.disabled=false;}
  };
}
async function requestLoginLink(button){
  if(state.busy)return;
  const field=$('email');if(!field.value.trim()||!field.checkValidity()){toast('Escribe primero tu correo electrónico.');field.focus();return;}
  state.busy=true;button.disabled=true;$('login-error').textContent='';
  try{
    const {error}=await db.auth.signInWithOtp({email:field.value.trim(),options:{shouldCreateUser:false,emailRedirectTo:new URL('./',location.href).href}});
    if(error)throw error;
    toast('Revisa tu correo. Copia el enlace del botón Sign in y pégalo aquí.');$('login-link').focus();
  }catch(error){$('login-error').textContent=errorMessage(error);}
  finally{state.busy=false;if(button.isConnected)button.disabled=false;}
}
function passwordModal(){
  modal(`${modalHeader('Crea tu contraseña')}<p class="modal-detail">Después podrás entrar con tu correo y contraseña desde la app instalada, sin pedir un nuevo enlace.</p><form id="password-form"><label for="new-password">Nueva contraseña</label><input id="new-password" name="password" type="password" autocomplete="new-password" minlength="12" maxlength="128" required><label for="confirm-password">Repite la contraseña</label><input id="confirm-password" name="confirmation" type="password" autocomplete="new-password" minlength="12" maxlength="128" required><p class="hint">Usa al menos 12 caracteres. Puedes guardarla en el gestor de contraseñas de tu iPhone.</p><p id="password-error" class="form-error" role="alert"></p><div class="row-actions">${btn('save-password','Guardar mi contraseña','check','primary','type="submit"')}</div></form>`);
  $('password-form').onsubmit=async e=>{
    e.preventDefault();if(state.busy)return;
    const form=e.currentTarget,errorField=$('password-error');
    const password=$('new-password').value,validation=passwordError(password,$('confirm-password').value);
    errorField.textContent=validation||'';if(validation)return;
    state.busy=true;const button=e.submitter;button.disabled=true;
    try{
      const {error}=await db.auth.updateUser({password});if(error)throw error;
      form.reset();closeModal();toast('Contraseña guardada. Ya puedes entrar con ella desde el icono de Ritmo.');
    }catch(error){errorField.textContent=errorMessage(error);}
    finally{state.busy=false;if(button.isConnected)button.disabled=false;}
  };
}

let calendarState=null;
const calendarScale=()=>state.calendarZoom==='large'?PIXELS_PER_MINUTE:2.4;
function weekdayPicker(id,t){const days=repeatDays(t||{});return `<fieldset class="weekday-picker" id="${id}"><legend>Repetir en estos días</legend><div class="weekday-choices">${WEEKDAYS.map((name,i)=>`<label><input type="checkbox" value="${i+1}" aria-label="${name}" ${days.includes(i+1)?'checked':''}><span>${['L','M','X','J','V','S','D'][i]}</span></label>`).join('')}</div><div class="weekday-presets">${[['work','Lunes a viernes'],['all','Todos'],['none','Ninguno']].map(([value,label])=>`<button type="button" data-action="repeat-preset" data-picker="${id}" data-days="${value}">${label}</button>`).join('')}</div><p class="hint">Se incluye al copiar la rutina solo en los días marcados. Sin selección, es una tarea puntual.</p></fieldset>`;}
const selectedDays=id=>[...$(id).querySelectorAll('input:checked')].map(i=>Number(i.value));
function renderDayCalendar(){return `<div class="segmented" role="group" aria-label="Vista de la agenda"><button data-action="day-view" data-mode="calendar" class="${state.dayView==='calendar'?'active':''}" aria-pressed="${state.dayView==='calendar'}">Calendario</button><button data-action="day-view" data-mode="list" class="${state.dayView==='list'?'active':''}" aria-pressed="${state.dayView==='list'}">Lista</button></div><div id="day-calendar-host">${state.dayView==='calendar'?calendarHTML(state.tasks,state.date,calendarState?.day===state.date?calendarState:null,calendarScale()):''}</div>`;}
function refreshCalendar(){const host=$('day-calendar-host');if(!host)return;const scroll=$('calendar-scroll')?.scrollTop||0;host.innerHTML=calendarHTML(state.tasks,state.date,calendarState,calendarScale());$('calendar-scroll').scrollTop=scroll;}
function scrollCalendar(){const viewport=$('calendar-scroll');if(!viewport)return;const hour=state.date===dateKey()?Math.max(0,clockMinutes(new Date())-viewport.clientHeight/(2*calendarScale())):360;viewport.scrollTop=hour*calendarScale();}
function beginCalendar(){if(state.date<dateKey()){toast('Los días anteriores conservan su registro. Elige hoy o un día futuro.');return;}calendarState=calendarDraft(state.tasks,state.date);if(!calendarState.items.length){toast('No hay bloques pendientes para mover. Puedes añadir una tarea.');calendarState=null;return;}state.dayView='calendar';render();scrollCalendar();}
function calendarBlockModal(id){const item=calendarState?.items.find(t=>t.id===id);if(!item)return;modal(`${modalHeader('Ajustar este bloque')}<p class="modal-detail">${esc(item.title)}. Cambia solo este día; el objetivo original se conserva.</p><label for="cal-start">Hora de inicio</label><input id="cal-start" type="time" value="${minuteClock(item.placed?item.start:state.date===dateKey()?clockMinutes(soon()):540)}"><label for="cal-minutes">Duración (minutos)</label><input id="cal-minutes" type="number" min="5" max="720" value="${Math.max(5,item.minutes)}"><label class="checkline"><input id="cal-fixed" type="checkbox" ${item.fixed_time?'checked':''}> Mantener esta hora fija hoy</label><div class="row-actions">${btn('calendar-update-block','Colocar en la propuesta','check','primary',`data-id="${id}"`)}${item.placed?btn('calendar-unplace','Dejar sin hueco','clock','',`data-id="${id}"`):''}</div>`);}
function calendarUpdate(id){const item=calendarState.items.find(t=>t.id===id),time=$('cal-start').value,minutes=Number($('cal-minutes').value);if(!time||!Number.isInteger(minutes)||minutes<5||minutes>720){toast('Elige una hora y entre 5 y 720 minutos.');return;}const [h,m]=time.split(':').map(Number),start=h*60+m;if(start+minutes>1439){toast('El bloque debe terminar antes de medianoche.');return;}Object.assign(item,{start,minutes,placed:true,fixed_time:$('cal-fixed').checked});closeModal();refreshCalendar();}
function calendarMessage(message){const status=$('calendar-status');if(status)status.querySelector('.calendar-status-message').textContent=message;}
async function previewCalendar(){if(!calendarState)return;const conflicts=calendarConflicts(calendarBlocks(state.tasks,state.date,calendarState));if(conflicts.length){calendarMessage(`«${conflicts[0][0].title}» se solapa con «${conflicts[0][1].title}». Mueve o acorta un bloque.`);$('calendar-status').classList.add('has-conflicts');return;}const request={plan_day:calendarState.day,items:calendarState.items.map(i=>({id:i.id,version:i.version,placed:i.placed,starts_at:i.placed?madridTime(calendarState.day,minuteClock(i.start)):null,minutes:i.minutes,fixed_time:i.fixed_time}))};await previewAdaptCalendar(request);}
async function previewAdaptCalendar(request){state.busy=true;try{const p=await rpc('ritmo_calendar',{request:{...request,apply:false}});pendingAdapt=request;pendingRpc='ritmo_calendar';modal(`${modalHeader('Guardar tu calendario')}<p class="modal-detail">Estos son tus horarios. Los huecos vacíos se conservan y los avisos seguirán el nuevo plan.</p>${adjustmentList(p.changes)}<div class="row-actions">${btn('apply-adapt','Guardar mi calendario','check','primary')}${btn('close-modal','Seguir ajustando')}</div>`);}catch(error){calendarMessage(errorMessage(error));$('calendar-status').classList.add('has-conflicts');}finally{state.busy=false;}}
function repeatModal(t,suggested=null){const day=addDays(state.date>=dateKey()?state.date:dateKey());modal(`${modalHeader('Repetir tarea')}<p class="modal-detail">${esc(t.title)}. Cada repetición tendrá su propio registro; podrás compararlas en Mi balance.</p><form id="repeat-form"><div class="two-col"><label>Día<input id="repeat-day" type="date" min="${dateKey()}" value="${day}" required></label><label>A qué hora<input id="repeat-time" type="time" value="${timeLabel(t.goal_starts_at||t.starts_at)}" required></label></div><label>Duración objetivo (min)<input id="repeat-minutes" type="number" min="5" max="720" value="${suggested||goalDuration(t)}" required></label>${suggested?`<p class="hint">Propuesta basada en tus repeticiones completas: ${formatDuration(suggested)}. Puedes cambiarla.</p>`:''}${weekdayPicker('repeat-weekdays',t)}<p class="hint">Puedes repetirla varias veces en un día, en horarios distintos.</p><div class="row-actions">${btn('save-repeat','Guardar repetición','calendar','primary','type="submit"')}</div></form>`);$('repeat-form').onsubmit=async e=>{e.preventDefault();try{const start=madridTime($('repeat-day').value,$('repeat-time').value),minutes=Number($('repeat-minutes').value),days=selectedDays('repeat-weekdays');await mutation(async()=>{await rpc('ritmo_repeat_task',{task_id:t.id,new_start:start,new_end:timeEnd(start,minutes),repeat_daily:days.length===7,repeat_days:days});toast('Repetición guardada. La anterior conserva su registro.');});}catch(error){toast(errorMessage(error));}};}
function comparisonBars(goal,real){const max=Math.max(goal,real,1);return `<div class="comparison-bars" aria-label="Objetivo ${formatDuration(goal)}, real ${formatDuration(real)}"><div><span>Objetivo <b>${formatDuration(goal)}</b></span><i class="goal-bar" style="width:${goal/max*100}%"></i></div><div><span>Real <b>${formatDuration(real)}</b></span><i class="real-bar" style="width:${real/max*100}%"></i></div></div>`;}
function renderRhythm(){const records=rhythmInsights(state.tasks).slice(0,12);return `<section class="card page-card habit-card"><h2>Tu ritmo real</h2><p class="intro">Objetivo y realidad, lado a lado. Las sugerencias usan hasta 7 repeticiones completas recientes. Las continuaciones parciales conservan su registro, pero no estiman cuánto cuesta completar toda la tarea.</p>${records.length?records.map(h=>{const max=Math.max(h.goal,...h.samples.map(s=>s.real),1),trend=h.improvement===null?'Aún faltan repeticiones para comparar tu evolución.':h.improvement>2?`Has bajado ${formatDuration(h.improvement)} respecto a tus primeras repeticiones (${formatDuration(h.first)} → ${formatDuration(h.latest)}).`:h.improvement< -2?`Últimas repeticiones: ${formatDuration(h.latest)}; primeras: ${formatDuration(h.first)}. Puede hacerte falta más margen.`:`Tu duración se mantiene estable: ${formatDuration(h.latest)} en las últimas repeticiones.`;return `<article class="rhythm-card"><h3>${esc(h.title)}</h3><div class="rhythm-numbers"><span>Objetivo<strong>${formatDuration(h.goal)}</strong></span><span>${h.count<3?'Primeros registros':'Habitual'}<strong>${formatDuration(h.typical)}</strong></span></div>${comparisonBars(h.goal,h.typical)}<div class="rhythm-history" role="img" aria-label="Últimos tiempos reales: ${h.samples.map(s=>s.real+' minutos').join(', ')}">${h.samples.map(s=>`<div><span>${formatDuration(s.real)}</span><i style="height:${Math.max(4,s.real/max*64)}px"></i><small>${new Date(s.at).toLocaleDateString('es-ES',{timeZone:'Europe/Madrid',day:'numeric',month:'numeric'})}</small></div>`).join('')}</div><p class="rhythm-trend">${esc(trend)}</p><p class="hint">${esc(h.advice)} ${h.count} ${h.count===1?'repetición registrada':'repeticiones registradas'}.</p>${btn('repeat-task',h.suggestion?'Preparar la próxima · '+h.suggestion+' min':'Repetir esta tarea','calendar','',`data-id="${h.taskId}" ${h.suggestion?`data-minutes="${h.suggestion}"`:''}`)}</article>`;}).join(''):'<div class="notice">Empieza y termina una tarea para registrar su tiempo real. Podrás repetirla desde su ficha.</div>'}</section>`;}

function todayTasks(){return state.tasks.filter(t=>taskDay(t)===state.date).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));}
function summary(tasks){return {done:tasks.filter(t=>t.status==='completed').length,closed:tasks.filter(t=>CLOSED.includes(t.status)).length,total:tasks.length,minutes:tasks.filter(t=>t.status==='completed').reduce((n,t)=>n+(actualDuration(t)||0),0)};}
function navHtml(mobile=false){return nav.map(([id,ic,label])=>`<button class="${mobile?'':'nav-btn '}${state.view===id?'active':''}" data-action="navigate" data-view="${id}" ${state.view===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span></button>`).join('');}
function render(){
  if(!state.user){renderLogin();return;}
  const heading={today:state.date===dateKey()?'Tu día, en orden':state.date===addDays(dateKey())?'Mañana, en orden':'Tu agenda',planning:'Haz espacio para mañana',balance:'Cada paso cuenta',settings:'A tu manera'}[state.view];
  $('app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-icon">r.</span>ritmo</div><nav aria-label="Navegación principal">${navHtml()}</nav><div class="sidebar-bottom"><p class="sidebar-note">No necesitas hacerlo todo.<br>Solo dar el siguiente paso.</p><div class="profile"><span class="avatar">N</span><div>Nicole<small>Mi espacio personal</small></div></div></div></aside><main class="main"><div class="mobile-brand"><div class="brand"><span class="brand-icon">r.</span>ritmo</div><span class="sync-status">${state.loading?'Sincronizando…':navigator.onLine?'Mi espacio personal':'Sin conexión'}</span></div><header class="topbar"><div><div class="eyebrow">${state.view==='today'?'Una cosa a la vez':'Mi espacio personal'}</div><h1>${heading}</h1><p class="date-line">${esc(dayLabel(state.date))}</p></div><div class="top-actions">${btn('navigate','<span>Preparar mañana</span>','calendar','', 'data-view="planning" aria-label="Preparar mañana"')}${btn('navigate','','bell','icon-only','data-view="settings" aria-label="Ajustes de notificaciones"')}</div></header>${!navigator.onLine?'<div class="offline-banner">Sin conexión. Puedes revisar lo que ya está cargado; conecta Internet para guardar cambios.</div>':''}${state.error?`<div class="notice error" role="alert">${esc(state.error)} ${btn('refresh','Reintentar')}</div>`:''}${state.loading&&!state.tasks.length?'<div class="empty">Cargando tu agenda…</div>':({today:renderToday,planning:renderPlanning,balance:renderBalance,settings:renderSettings}[state.view])()}<p class="sync-line">Europe/Madrid · ${state.loading?'Sincronizando…':'Los cambios se guardan en tu cuenta'}</p></main><nav class="mobile-nav" aria-label="Navegación móvil">${navHtml(true)}</nav></div>`;
}
function focusCard(tasks){
  const t=currentTask(tasks), now=new Date();if(!t)return `<section class="focus-card"><div class="focus-top"><span class="focus-label">${icon('spark')} ESPACIO PARA TI</span></div><h2>${tasks.some(t=>t.status==='deferred')?'Tienes tareas por recolocar.':tasks.length?'Tu agenda está revisada.':'Tu día empieza aquí.'}</h2><p class="focus-note">${tasks.some(t=>t.status==='deferred'||t.status==='continued')?'Puedes recuperar los bloques sin horario con Reorganizar mi día.':tasks.length?'Has cerrado todos los bloques de este día. Revisa el balance y prepara el siguiente.':'Pega el plan que preparemos en el chat. Antes de guardarlo podrás revisar los horarios.'}</p><div class="row-actions">${tasks.some(t=>t.status==='deferred'||t.status==='continued')?btn('adjust-day','Reorganizar mi día','calendar','lime'):btn('navigate','Preparar el plan','calendar','lime','data-view="planning"')}</div></section>`;
  const future=new Date(t.starts_at)>now, active=t.status==='active', overdue=active&&new Date(t.ends_at)<now;
  const remaining=Math.max(0,Math.ceil((new Date(active?t.ends_at:t.starts_at)-now)/60000));
  const label=overdue?'ES MOMENTO DE CAMBIAR':active?'AHORA, TU FOCO':future?'TU SIGUIENTE PASO':'PUEDES EMPEZAR AQUÍ';
  return `<section class="focus-card"><div class="focus-top"><span class="focus-label">${icon('spark')} ${label}</span><span class="focus-category">${CATEGORIES[t.category]}</span></div><h2>${esc(t.title)}</h2>${t.notes?`<p class="focus-note">${esc(t.notes)}</p>`:''}<div class="focus-time"><strong>${active&&!overdue?formatDuration(remaining):timeLabel(t.starts_at)}</strong><span>${active&&!overdue?'para el siguiente bloque':`${timeLabel(t.ends_at)} · ${formatDuration(duration(t))}`}</span></div><div class="focus-actions">${active?btn('review','Terminar bloque','check','lime',`data-id="${t.id}"`):btn('start','Empezar tarea','play','lime',`data-id="${t.id}"`)}${btn('review','Reprogramar','calendar','subtle',`data-id="${t.id}" data-mode="continued"`)}</div><div class="focus-footer">${icon('clock')} ${overdue?'Te estás pasando del tiempo previsto. Cierra este bloque y cambia de tarea; el resto se reajusta.':future?`Tienes ${formatDuration(remaining)} libres hasta el siguiente bloque.`:'Tu progreso se mide en pasos, no en perfección.'}</div></section>`;
}
function timingDetail(t){const goal=`Objetivo: ${timeLabel(t.goal_starts_at||t.starts_at)}–${timeLabel(t.goal_ends_at||t.ends_at)} · ${formatDuration(goalDuration(t))}`;return `<div class="task-timing">${esc(goal)}${t.fixed_time?' · Horario fijo':''}${t.actual_start?`<br>Real: ${timeLabel(t.actual_start)}–${t.actual_end?timeLabel(t.actual_end):'en curso'} · ${formatDuration(actualDuration(t))}`:t.goal_starts_at&&new Date(t.goal_starts_at).getTime()!==new Date(t.starts_at).getTime()?' · Horario reajustado':''}</div>`;}
function taskRows(tasks){return tasks.map(t=>{
  const canSwipe=state.view==='today'&&['pending','deferred'].includes(t.status);
  const detail=`<button class="task-open" data-action="detail" data-id="${t.id}" aria-label="Ver ${esc(t.title)}">${icon(CLOSED.includes(t.status)?'check':t.status==='active'?'clock':'edit')}</button>`;
  const controls=canSwipe?`<div class="task-row-actions"><button class="task-swipe-toggle" data-action="swipe-toggle" aria-label="Opciones de ${esc(t.title)}" aria-expanded="false" aria-controls="swipe-actions-${t.id}">···</button>${detail}</div>`:detail;
  const card=`<article class="task-row category-${t.category} ${t.status==='active'?'current':''} ${CLOSED.includes(t.status)?'closed':''}"><div class="task-time">${t.status==='deferred'?'Sin hueco':timeLabel(t.actual_start&&t.actual_end?t.actual_start:t.starts_at)}<small>${t.status==='deferred'?'Recolocar':timeLabel(t.actual_start&&t.actual_end?t.actual_end:t.ends_at)}</small></div><div class="task-info"><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span>${CATEGORIES[t.category]}</span><span>·</span><span>${formatDuration(duration(t))}</span>${t.priority==='alta'?'<span>· Prioridad alta</span>':''}${repeatLabel(t)?`<span>· ${esc(repeatLabel(t))}</span>`:''}<span class="task-status">${STATUS[t.status]}</span></div>${timingDetail(t)}${t.status==='deferred'?btn('organize-focus','Buscar hueco hoy','calendar','small',`data-id="${t.id}"`):''}</div>${controls}</article>`;
  return canSwipe?`<div class="task-swipe" data-swipe-id="${t.id}">${card}<div class="task-swipe-actions" id="swipe-actions-${t.id}" aria-hidden="true" inert><button class="swipe-delete" data-action="swipe-delete" data-id="${t.id}" aria-label="Eliminar ${esc(t.title)}">${icon('trash')}<span>Eliminar</span></button></div></div>`:card;
}).join('');}
function renderToday(){
  const tasks=todayTasks(),s=summary(tasks),priorities=tasks.filter(t=>t.priority==='alta'&&!CLOSED.includes(t.status)).slice(0,3);
  const filtered=tasks.filter(t=>state.filter==='all'||(state.filter==='open'?!CLOSED.includes(t.status):CLOSED.includes(t.status)));
  return `<div class="layout"><div>${focusCard(tasks)}${recoveryBanner(tasks)}<div class="section-head"><h2>Tu agenda</h2><div class="date-control">${btn('previous-day','','back','icon-only','aria-label="Día anterior"')}<input type="date" id="agenda-date" value="${state.date}" aria-label="Fecha de la agenda">${btn('next-day','','next','icon-only','aria-label="Día siguiente"')}${btn('new-task','Añadir','plan')}</div></div><div class="agenda-adjust"><div class="row-actions">${btn('adjust-day','Reorganizar mi día','clock')}${btn('trash','Papelera','trash')}</div><p>Recupera tareas, cambia su orden o libera tiempo. Tú eliges qué horas mantener fijas hoy.</p></div>${renderDayCalendar()}<div class="segmented" ${state.dayView==='calendar'?'hidden':''} role="group" aria-label="Filtrar tareas">${[['all','Todas'],['open','Por hacer'],['closed','Revisadas']].map(([f,l])=>`<button class="${state.filter===f?'active':''}" data-action="filter" data-filter="${f}">${l}</button>`).join('')}</div>${state.dayView==='list'&&filtered.some(t=>['pending','deferred'].includes(t.status))?'<p class="swipe-hint">Desliza una tarea pendiente a la izquierda para eliminarla, o toca ···.</p>':''}<div class="task-list">${state.dayView==='calendar'?'':filtered.length?taskRows(filtered):'<div class="empty">'+(tasks.length?'No hay tareas en este filtro.':'Este día aún tiene la agenda vacía.')+'</div>'}</div></div><aside class="right-stack"><section class="card progress-card"><h2>Un paso más cerca</h2><div class="progress-ring" style="--progress:${s.total?s.done/s.total*100:0}%"><div class="progress-number">${s.done}<small>de ${s.total} completadas</small></div></div><p class="progress-caption">${s.total===0?'Prepara tu primer día.':s.done===s.total?'Has cumplido lo que te propusiste.':'Cada bloque cuenta.'}</p><div class="mini-stats"><div><strong>${formatDuration(s.minutes)}</strong><span>Tiempo real completado</span></div><div><strong>${s.closed}</strong><span>Bloques revisados</span></div></div></section><section class="card"><h2>Lo que importa hoy</h2><div class="priority-list">${priorities.length?priorities.map((t,i)=>`<div class="priority-item"><span class="priority-mark">0${i+1}</span><div><strong>${esc(t.title)}</strong><small>${timeLabel(t.starts_at)} · ${CATEGORIES[t.category]}</small></div></div>`).join(''):'<p class="muted" style="font-size:.9rem;line-height:1.6">Tus prioridades están al día. Puedes revisar el balance.</p>'}</div></section><section class="card notification-card"><h2>${icon('bell')} Un pequeño empujón</h2><p>${state.notifications?'Avisos 2 minutos antes, al empezar y cada 5 minutos hasta que revises o empieces el bloque pendiente.':'Activa los avisos en tu móvil para recordar cada cambio de tarea, incluso con la app cerrada.'}</p>${btn('navigate',state.notifications?'Revisar mis avisos':'Configurar mis avisos','bell','','data-view="settings"')}</section></aside></div>`;
}
function carryTasks(){const linked=new Set(state.tasks.map(t=>t.source_task_id).filter(Boolean));return state.tasks.filter(t=>dateKey(new Date(t.starts_at))<=state.date&&['pending','active','continued','postponed','deferred'].includes(t.status)&&!linked.has(t.id)).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));}
let planningDay='',planningText='';
function renderPlanning(){const next=planningDay||addDays(state.date),carry=carryTasks();return `<section class="card page-card"><div class="eyebrow">Cerrar hoy · preparar mañana</div><h2>Tu próxima agenda empieza en ChatGPT</h2><p class="intro">Lleva el contexto a cualquier conversación de ChatGPT. Añade tus nuevas tareas y pega aquí el plan que te devuelva.</p><label for="plan-date">Día que vamos a preparar</label><input type="date" id="plan-date" value="${next}" required><p class="hint">El balance corresponde al ${esc(dayLabel(state.date))} (${state.date}). La rutina y la agenda corresponden al día elegido arriba.</p><div class="planning-export"><button class="btn primary" data-action="copy-chat-all">${icon('copy')} Copiar todo para ChatGPT</button><p>Incluye las tres partes. Copiar texto conserva tu agenda tal como está.</p><div class="planning-parts">${[['instructions','1. Instrucciones y ejemplo','El formato que debe devolver ChatGPT.'],['balance','2. Balance e historial','Resultados, pendientes y tiempos de tus repeticiones.'],['agenda','3. Rutina y agenda del día','Los días de repetición y los bloques ya programados.']].map(([part,label,detail])=>`<div><strong>${label}</strong><p>${detail}</p>${btn('copy-chat-part','Copiar esta parte','copy','',`data-part="${part}"`)}</div>`).join('')}</div></div><div class="planning-routine"><h3>Programar sin pasar por el chat</h3><p>Puedes añadir directamente la rutina que corresponda al día elegido. Se conservan las horas ocupadas; después puedes reorganizarla.</p>${btn('schedule-routine','Revisar y programar rutina','calendar')}</div><label for="plan-text">Pega el plan de ChatGPT</label><textarea id="plan-text" rows="9" placeholder='{"tasks":[{"start":"07:00","end":"07:20","title":"Paseo","category":"personal","priority":"alta","recurrence_days":[1,2,3,4,5],"fixed_time":false}]}'>${esc(planningText)}</textarea><p class="hint">También acepta una tarea por línea: 07:00-07:30 | Paseo | personal | alta | Nota. El JSON conserva las referencias de las tareas que ya conoces.</p>${btn('preview-plan','Revisar antes de guardar','check','primary')}<p id="plan-error" role="alert" class="form-error"></p></section><div class="section-head"><h2>Para recuperar o continuar</h2><span class="muted">${carry.length} tareas</span></div><section class="card page-card carry-list">${carry.length?carry.map(t=>`<div class="carry-item"><div><strong>${esc(t.title)}</strong><p>${dayLabel(taskDay(t))} · ${STATUS[t.status]}${t.review?' · '+esc(t.review):''}</p></div>${btn('schedule-carry','Elegir otro momento','calendar','',`data-id="${t.id}"`)}</div>`).join(''):'<p class="muted">No tienes tareas por recuperar. Puedes preparar un día nuevo.</p>'}</section>`;}
function renderBalance(){const tasks=todayTasks(),s=summary(tasks);return `<section class="card page-card"><div class="section-head" style="margin-top:0"><h2>Así ha ido tu día</h2><input type="date" id="agenda-date" value="${state.date}" aria-label="Fecha del balance" style="max-width:170px"></div><p class="intro">Completar, continuar y reprogramar son decisiones. Aquí queda registrado lo que pasó.</p><div class="summary-stats"><div class="stat-block"><strong>${s.done}</strong><span>Completadas</span></div><div class="stat-block"><strong>${tasks.filter(t=>t.status==='continued').length}</strong><span>Continuaciones</span></div><div class="stat-block"><strong>${tasks.filter(t=>t.status==='postponed').length}</strong><span>Reprogramadas</span></div></div><div class="task-list">${taskRows(tasks)||'<div class="empty">No hay tareas este día.</div>'}</div><div class="row-actions">${btn('copy-summary','Copiar resumen del día','copy','primary')}${btn('export-data','Descargar mi registro','download')}</div></section>${renderRhythm()}`;}
function renderSettings(){const support=pushSupport();const permission='Notification'in window?Notification.permission:'unsupported';return `<section class="card page-card"><h2>Recordatorios que te acompañan</h2><p class="intro">Dos minutos antes de cada bloque, al empezar y cada cinco minutos si falta empezar o cerrar la tarea. Los avisos se detienen al tomar una decisión sobre ella.</p><div class="setting-row"><div><h3>Instalar en el móvil</h3><p>iPhone: Safari → Compartir → Añadir a pantalla de inicio. Después abre Ritmo desde el icono. Los avisos necesitan iOS 16.4 o posterior.<br>Android: menú del navegador → Instalar aplicación o Añadir a pantalla de inicio.</p></div>${btn('install','Cómo instalar','download')}</div><div class="setting-row"><div><h3>Avisos en este dispositivo</h3><p id="push-status">${!support.supported?esc(support.message):permission==='denied'?'Permiso bloqueado. Activa las notificaciones en los ajustes del navegador o del móvil.':state.notifications?'Recordatorios activados en tu cuenta. Comprueba también este dispositivo.':'Activa los avisos desde el móvil en el que quieres recibirlos.'}</p></div>${btn('enable-push','Activar en este dispositivo','bell','primary',support.supported?'':'disabled')}</div><div class="setting-row"><div><h3>Comprobar los avisos</h3><p>Envía un aviso de prueba a este dispositivo y comprueba que aparece.</p></div>${btn('test-push','Enviar prueba','bell','',support.supported?'':'disabled')}</div><div class="setting-row"><div><h3>Pausar los recordatorios</h3><p>Puedes silenciarlos en todos tus dispositivos y volver a activarlos cuando quieras.</p></div>${btn('disable-push','Pausar avisos','clock')}</div><div class="setting-row"><div><h3>Horario y privacidad</h3><p>Tu agenda usa la hora de Madrid y se guarda en tu cuenta. Los avisos de tareas se limitan al día en curso. Los datos de la agenda requieren iniciar sesión.</p></div></div>${state.health?`<p class="sync-line">Última comprobación de recordatorios: ${esc(new Date(state.health.checked_at).toLocaleString('es-ES',{timeZone:'Europe/Madrid'}))}</p>`:'<div class="notice">El envío depende de tu conexión, los permisos del móvil y sus modos de concentración. Los avisos pueden retrasarse.</div>'}<div class="setting-row"><div><h3>Acceso con contraseña</h3><p>Si ya tienes sesión en Safari, crea aquí tu contraseña. Después entra con ella desde el icono de Ritmo, sin solicitar más correos.</p></div>${btn('password-setup','Crear o cambiar contraseña','edit')}</div><div class="setting-row"><div><h3>Tareas eliminadas</h3><p>Puedes recuperar una tarea desde la papelera. Al eliminarla se detienen sus avisos.</p></div>${btn('trash','Abrir papelera','trash')}</div><div class="setting-row"><div><h3>Tu sesión</h3><p>${esc(state.user.email)}</p></div>${btn('logout','Cerrar sesión','logout')}</div></section>`;}
async function load(initial=false){
  if(!state.user||calendarState)return;const scroll=$('calendar-scroll')?.scrollTop;state.loading=true;state.error=null;
  try{
    const owner=await db.from('ritmo_owners').select('user_id,notifications_enabled').eq('user_id',state.user.id).maybeSingle();if(owner.error)throw owner.error;if(!owner.data)throw new Error('Esta cuenta no tiene acceso a Ritmo. Usa el correo autorizado para esta agenda.');
    const tasks=[];for(let offset=0;;offset+=1000){const {data,error}=await db.from('ritmo_tasks').select('*').neq('status','deleted').order('starts_at').order('id').range(offset,offset+999);if(error)throw error;tasks.push(...data);if(data.length<1000)break;}state.tasks=tasks;state.notifications=owner.data.notifications_enabled;
    if(initial&&!todayTasks().length){const next=state.tasks.find(t=>new Date(t.starts_at)>new Date());if(next)state.date=dateKey(new Date(next.starts_at));}
    const health=await db.from('ritmo_health').select('checked_at').eq('id',1).maybeSingle();if(!health.error)state.health=health.data;
  }catch(error){state.error=errorMessage(error);}finally{state.loading=false;render();if($('calendar-scroll')){if(scroll!==undefined)$('calendar-scroll').scrollTop=scroll;else scrollCalendar();}}
}
async function mutation(fn){if(state.busy)return;if(!navigator.onLine){toast('Conecta Internet para guardar este cambio.');return;}state.busy=true;document.querySelectorAll('#modal button').forEach(b=>b.disabled=true);try{await fn();closeModal();await load();return true;}catch(error){toast(errorMessage(error));return false;}finally{state.busy=false;document.querySelectorAll('#modal button').forEach(b=>b.disabled=false);}}
function getTask(id){return state.tasks.find(t=>t.id===id);}
async function rpc(name,args){const {data,error}=await db.rpc(name,args);if(error)throw error;return data;}
let pendingAdapt,pendingRpc='ritmo_adapt',organizerState;
function adjustmentList(changes){return changes.length?`<div class="preview-list">${changes.map(t=>`<div class="preview-item"><strong>${t.status==='deferred'?'Recolocar':timeLabel(t.starts_at)+'–'+timeLabel(t.ends_at)}</strong><span>${esc(t.title)}<br><small class="muted">Antes: ${timeLabel(t.old_start)}–${timeLabel(t.old_end)}${t.fixed_time?' · Horario fijo':''}${t.status==='deferred'?(t.reason==='not_today'?' · La dejas pendiente para otro día.':' · No queda hueco; sigue pendiente.'):t.continuation?' · Nuevo bloque para retomar.':''}</small></span></div>`).join('')}</div>`:'<p class="modal-detail">El resto de la agenda mantiene su horario.</p>';}
async function previewAdapt(request,title='Así se reajusta tu día'){
  if(state.busy)return;state.busy=true;
  try{const preview=await rpc('ritmo_adapt',{request:{...request,apply:false}});pendingAdapt=request;pendingRpc='ritmo_adapt';modal(`${modalHeader(title)}<p class="modal-detail">${esc(preview.fixed_windows)} Tu horario objetivo se conserva en el balance.</p>${adjustmentList(preview.changes)}<p class="hint">El ajuste se calcula de nuevo al guardar, según la hora real.</p><div class="row-actions">${btn('apply-adapt','Guardar este ajuste','check','primary')}${btn('close-modal','Cancelar')}</div>`);}finally{state.busy=false;}
}
async function startTask(t){const other=state.tasks.find(x=>x.status==='active'&&x.id!==t.id);if(other){toast('Cierra primero el bloque que sigue en curso.');reviewModal(other);return;}await previewAdapt({action:'start',task_id:t.id},'Empezar ahora');}
function recoveryBanner(tasks){const recovery=organizerItems(state.tasks,state.date).filter(t=>t.recover);return recovery.length?`<section class="recovery-banner"><div><strong>${recovery.length} ${recovery.length===1?'tarea por recolocar':'tareas por recolocar'}</strong><p>${recovery.map(t=>esc(t.title)).join(' · ')}</p></div>${btn('adjust-day','Encontrarles hueco','calendar','primary')}</section>`:'';}
function soon(){return new Date(Math.ceil(Date.now()/60000)*60000+120000);}
function adjustDayModal(focusId=null){const items=organizerItems(state.tasks,state.date);if(!items.length){toast('No hay tareas pendientes para reorganizar este día.');return;}if(focusId){const i=items.findIndex(t=>t.id===focusId);if(i>0)items.unshift(...items.splice(i,1));}const active=state.tasks.find(t=>t.status==='active'),start=state.date===dateKey()?timeLabel(active&&new Date(active.ends_at)>soon()?active.ends_at:soon()):'07:00';const last=todayTasks().reduce((s,t)=>{const end=timeLabel(t.goal_ends_at||t.ends_at);return end>s?end:s;},'21:30');organizerState={day:state.date,start,end:last>start?last:'23:59',items};renderOrganizer();}
function organizerRows(){return organizerState.items.map((t,i)=>`<div class="organize-row" data-id="${t.id}"><div class="organize-title"><label class="checkline"><input type="checkbox" class="org-include" ${t.include?'checked':''} aria-label="Hacer hoy: ${esc(t.title)}"><span>${esc(t.title)}${t.recover?'<small>Por recolocar</small>':t.priority==='alta'?'<small>Prioridad alta</small>':''}</span></label><div class="order-buttons">${btn('organize-up','↑','','icon-only',`data-id="${t.id}" aria-label="Dar prioridad a ${esc(t.title)}" ${i===0?'disabled':''}`)}${btn('organize-down','↓','','icon-only',`data-id="${t.id}" aria-label="Bajar prioridad de ${esc(t.title)}" ${i===organizerState.items.length-1?'disabled':''}`)}</div></div><div class="organize-controls"><label>Duración (min)<input type="number" class="org-minutes" min="5" max="720" value="${t.minutes}" aria-label="Minutos para ${esc(t.title)}"></label><label class="checkline"><input type="checkbox" class="org-fixed" ${t.fixed_time?'checked':''} aria-label="Hora fija para ${esc(t.title)}"> Hora fija hoy</label><label ${t.fixed_time?'':'hidden'}>A las<input type="time" class="org-time" value="${timeLabel(t.starts_at)}" aria-label="Hora de ${esc(t.title)}"></label></div></div>`).join('');}
function renderOrganizer(){const o=organizerState;modal(`${modalHeader('Reorganizar mi día')}<p class="modal-detail">Elige qué hacer hoy. Ajusta los minutos, las prioridades y las horas fijas.</p><div class="organizer-window"><label>Desde<input aria-label="Empezar desde" id="organizer-start" type="time" value="${o.start}" required></label><label>Hasta<input aria-label="Acabar antes de" id="organizer-end" type="time" value="${o.end}" required></label></div><div class="row-actions organizer-shortcuts">${o.day===dateKey()?btn('organize-now','Desde ahora','clock'):''}${btn('organize-no-cooking','Hoy no cocino','spark')}</div><p class="hint">Sin cocinar: hasta 30 min para comer. Desmarca lo que dejas para otro día.</p><div id="organizer-items">${organizerRows()}</div><p id="organizer-error" class="form-error" role="alert"></p><div class="organizer-footer">${btn('preview-organizer','Ver cómo queda mi día','calendar','primary')}</div>`);}
function collectOrganizer(){organizerState.start=$('organizer-start').value;organizerState.end=$('organizer-end').value;for(const row of document.querySelectorAll('.organize-row')){const t=organizerState.items.find(t=>t.id===row.dataset.id);t.include=row.querySelector('.org-include').checked;t.minutes=Number(row.querySelector('.org-minutes').value);t.fixed_time=row.querySelector('.org-fixed').checked;const time=row.querySelector('.org-time').value;if(time)t.starts_at=madridTime(organizerState.day,time);}return organizerState;}
async function previewOrganizer(){try{const o=collectOrganizer();if(!o.start||!o.end||o.end<=o.start)throw new Error('Elige un inicio y un fin posterior, dentro del mismo día.');if(o.items.some(t=>!Number.isInteger(t.minutes)||t.minutes<5||t.minutes>720))throw new Error('Las duraciones deben estar entre 5 y 720 minutos.');state.busy=true;const request={plan_day:o.day,window_start:madridTime(o.day,o.start),window_end:madridTime(o.day,o.end),items:o.items.map(({id,minutes,fixed_time,include:chosen,starts_at})=>({id,minutes,fixed_time,include:chosen,starts_at}))};const p=await rpc('ritmo_reorganize',{request:{...request,apply:false}});pendingAdapt=request;pendingRpc='ritmo_reorganize';modal(`${modalHeader('Así queda tu día')}<div class="notice">${p.restored} tareas recuperadas · ${p.unplaced} por recolocar. Horario: ${timeLabel(p.window_start)}–${timeLabel(p.window_end)}.</div>${p.unplaced?'<p class="hint">Si quieres recuperar más bloques, reduce una duración, cambia prioridades o amplía la hora de fin. Las pendientes se conservan.</p>':''}${adjustmentList(p.changes)}<div class="row-actions">${btn('apply-adapt','Guardar mi día','check','primary')}${btn('back-organizer','Cambiar el ajuste','edit')}</div>`);}catch(error){if($('organizer-error'))$('organizer-error').textContent=errorMessage(error);else toast(errorMessage(error));}finally{state.busy=false;}}
function organizerMove(id,step){collectOrganizer();const i=organizerState.items.findIndex(t=>t.id===id),j=i+step;if(i<0||j<0||j>=organizerState.items.length)return;[organizerState.items[i],organizerState.items[j]]=[organizerState.items[j],organizerState.items[i]];$('organizer-items').innerHTML=organizerRows();}
function renderHabits(){const records=habits(state.tasks).slice(0,12);return `<section class="card page-card habit-card"><h2>Tu ritmo real</h2><p class="intro">Comparar lo previsto con lo vivido te ayuda a preparar días más realistas. La duración habitual es la mediana de los bloques completados o continuados con inicio y fin registrados.</p>${records.length?records.map(h=>`<div class="habit-row"><strong>${esc(h.title)}</strong><span>Objetivo medio: ${formatDuration(h.goal)} · ${h.count>=3?'Habitual':'Primeros registros'}: ${formatDuration(h.typical)}</span><small>${h.count} ${h.count===1?'registro':'registros'}${h.count<3?' · Aún hay pocos datos para ver una tendencia.':''}</small></div>`).join(''):'<div class="notice">Empieza y cierra tus bloques. Aquí aparecerán sus tiempos reales; no se estiman a partir de tareas que solo marcaste como terminadas.</div>'}</section>`;}
function detailModal(t){modal(`${modalHeader(t.title)}<p class="modal-detail">${esc(dayLabel(dateKey(new Date(t.starts_at))))}<br>${timeLabel(t.starts_at)}–${timeLabel(t.ends_at)} (${formatDuration(duration(t))}) · ${CATEGORIES[t.category]} · ${STATUS[t.status]}${repeatLabel(t)?`<br>Se repite: ${esc(repeatLabel(t))}`:''}</p>${timingDetail(t)}${t.notes?`<div class="notice">${esc(t.notes)}</div>`:''}${t.review?`<p class="modal-detail"><strong>Tu resultado:</strong> ${esc(t.review)}${t.rating?` · ${t.rating}/5`:''}</p>`:''}<div class="row-actions">${!CLOSED.includes(t.status)?`${t.status==='pending'?btn('start','Empezar','play','primary',`data-id="${t.id}"`):''}${btn('review','Evaluar bloque','check','',`data-id="${t.id}"`)}${['pending','deferred','continued'].includes(t.status)?btn('organize-focus','Mover y reorganizar','calendar','',`data-id="${t.id}"`):''}${['pending','deferred'].includes(t.status)?btn('edit-task','Editar','edit','',`data-id="${t.id}"`):t.status==='deferred'?btn('schedule-carry','Elegir otro momento','calendar','',`data-id="${t.id}"`):''}`:btn('schedule-carry','Programar otro bloque','calendar','',`data-id="${t.id}"`)}${btn('repeat-task','Repetir tarea','copy','',`data-id="${t.id}"`)}</div><div class="task-delete-area">${btn('delete-task','Eliminar tarea','trash','danger',`data-id="${t.id}"`)}</div>`);}

function deleteTaskModal(t){modal(`${modalHeader('Eliminar tarea')}<p class="modal-detail"><strong>${esc(t.title)}</strong></p><p class="modal-detail">Este bloque saldrá de tu agenda y dejará de enviar avisos. Podrás recuperarlo desde la papelera.</p>${t.status==='active'?'<div class="notice">Se detendrá el bloque en curso y se conservará el tiempo trabajado.</div>':''}<p class="hint">Otros días y continuaciones se conservan.</p><div class="row-actions">${btn('confirm-delete','Eliminar tarea','trash','danger',`data-id="${t.id}"`)}${btn('close-modal','Cancelar')}</div>`);}
function deleteUndo(removed){toast('Tarea eliminada.');const undo=document.createElement('button');undo.type='button';undo.className='toast-undo';undo.dataset.action='restore-task';undo.dataset.id=removed.id;undo.setAttribute('aria-label','Deshacer eliminación');undo.textContent='Deshacer';$('toast').append(undo);}
async function deleteTask(t,{quick=false}={}){let removed;await mutation(async()=>{removed=await rpc('ritmo_delete_task',{task_id:t.id});state.tasks=state.tasks.filter(task=>task.id!==removed.id);});if(removed&&quick){deleteUndo(removed);return;}if(removed)modal(`${modalHeader('Tarea eliminada')}<p class="modal-detail">${esc(removed.title)} está en la papelera. Sus avisos se han detenido.</p><div class="row-actions">${btn('restore-task','Deshacer eliminación','back','primary',`data-id="${removed.id}"`)}${btn('close-modal','Volver a mi día')}</div>`);}
async function trashModal(){const {data,error}=await db.from('ritmo_tasks').select('id,title,starts_at,deleted_at').eq('status','deleted').order('deleted_at',{ascending:false});if(error)throw error;modal(`${modalHeader('Papelera')}<p class="modal-detail">Las tareas de aquí no ocupan tiempo ni envían avisos. Puedes recuperarlas cuando quieras.</p><div class="trash-list">${data.length?data.map(t=>`<div class="trash-item"><div><strong>${esc(t.title)}</strong><small>${esc(dayLabel(dateKey(new Date(t.starts_at))))}</small></div>${btn('restore-task','Recuperar','back','',`data-id="${t.id}" aria-label="Recuperar ${esc(t.title)}"`)}</div>`).join(''):'<div class="empty">La papelera está vacía.</div>'}</div>`);}

let reviewState;
function reviewModal(t,mode='completed'){reviewState={task:t,mode,rating:null};modal(`${modalHeader('¿Cómo ha ido el bloque?')}<p class="modal-detail">${esc(t.title)}</p><div class="review-options">${[['completed','check','La he terminado'],['continued','clock','Quiero continuar después'],['postponed','calendar','La paso a otro día'],['skipped','close','Ya no necesito hacerla']].map(([m,ic,label])=>btn('review-mode',label,ic,m===mode?'active':'',`data-mode="${m}"`)).join('')}</div><div id="review-schedule">${reviewSchedule()}</div>${t.status==='active'&&new Date(t.ends_at)>new Date()?`<fieldset class="early-choice"><legend>Has terminado antes. ¿Qué prefieres?</legend><label><input type="radio" name="finish-mode" value="keep" checked> Mantener mis horarios y disfrutar del tiempo libre; avisarme cuando toque la próxima tarea</label><label><input type="radio" name="finish-mode" value="advance"> Adelantar las tareas siguientes y poder empezar con la próxima</label><p class="hint">Los bloques fijos mantienen su hora en ambos casos.</p></fieldset>`:t.status==='active'?'<div class="notice">El resto se ajusta al tiempo real de este bloque. Trabajo y comida conservan su horario.</div>':''}<label for="review-note">¿Qué has conseguido o qué falta? <span class="muted">(opcional)</span></label><textarea id="review-note" rows="3" maxlength="4000" placeholder="Déjate una nota para retomar el hilo"></textarea><label>¿Cómo te has sentido? <span class="muted">(opcional)</span></label><div class="rating-row" aria-label="Valorar el bloque">${[1,2,3,4,5].map(n=>`<button data-action="rate" data-rating="${n}" aria-label="${n} de 5">${n}</button>`).join('')}</div><div class="row-actions">${btn('save-review','Guardar y dar el siguiente paso','check','primary')}</div>`);}
function reviewSchedule(){const t=reviewState.task;if(reviewState.mode==='continued')return `<fieldset class="continue-choice"><legend>¿Cuándo quieres retomarla?</legend><label><input type="radio" name="continue-kind" value="auto" checked> Buscar un hueco y avisarme</label><label><input type="radio" name="continue-kind" value="manual"> Elegir yo la hora</label><label><input type="radio" name="continue-kind" value="park"> Dejarla pendiente sin aviso</label></fieldset><div id="continue-fields"><div class="two-col"><label>Día para retomar<input id="continue-day" type="date" value="${state.date>=dateKey()?state.date:dateKey()}" min="${dateKey()}"></label><label>Tiempo que falta (min)<input id="continue-minutes" type="number" min="5" max="720" value="${Math.max(5,Math.min(30,goalDuration(t)))}"></label></div><label id="continue-time-label" hidden>A qué hora<input id="continue-time" type="time" value="${timeLabel(soon())}"></label></div><p id="continue-explanation" class="hint">Guardaremos un nuevo bloque para que vuelvas a recibir avisos cuando toque retomarlo.</p>`;if(reviewState.mode!=='postponed')return '';return `<div class="two-col"><div><label for="review-day">Nuevo día</label><input id="review-day" type="date" value="${addDays(dateKey(new Date(t.starts_at)))}"></div><div><label for="review-time">A qué hora</label><input id="review-time" type="time" value="${timeLabel(t.starts_at)}"></div></div>`;}
function scheduleModal(t){modal(`${modalHeader('Dale otro momento')}<p class="modal-detail">${esc(t.title)} · ${formatDuration(goalDuration(t))} de objetivo</p><form id="schedule-form"><div class="two-col"><div><label for="carry-day">Día</label><input id="carry-day" type="date" required value="${addDays(state.date)}"></div><div><label for="carry-time">Hora de inicio</label><input id="carry-time" type="time" required value="${timeLabel(t.starts_at)}"></div></div><label for="carry-duration">Duración en minutos</label><input id="carry-duration" type="number" min="5" max="720" value="${goalDuration(t)}" required><div class="row-actions">${btn('save-carry','Guardar nuevo bloque','calendar','primary',`data-id="${t.id}" type="submit"`)}</div></form>`);$('schedule-form').onsubmit=e=>{e.preventDefault();saveCarry(t);};}
function editModal(t=null){modal(`${modalHeader(t?'Editar tarea':'Un nuevo bloque')}<form id="task-form"><label for="task-title">Tarea</label><input id="task-title" maxlength="200" required value="${esc(t?.title||'')}" placeholder="¿A qué quieres dedicar este rato?"><div class="two-col"><div><label for="task-day">Día</label><input id="task-day" type="date" value="${t?dateKey(new Date(t.starts_at)):state.date}" required></div><div><label for="task-category">Área</label><select id="task-category">${Object.entries(CATEGORIES).map(([k,v])=>`<option value="${k}" ${t?.category===k?'selected':''}>${v}</option>`).join('')}</select></div><div><label for="task-start">Empieza</label><input id="task-start" type="time" required value="${t?timeLabel(t.starts_at):'09:00'}"></div><div><label for="task-end">Termina</label><input id="task-end" type="time" required value="${t?timeLabel(t.ends_at):'09:30'}"></div></div><label for="task-priority">Prioridad</label><select id="task-priority">${['alta','media','baja'].map(p=>`<option value="${p}" ${t?.priority===p||!t&&p==='media'?'selected':''}>${p[0].toUpperCase()+p.slice(1)}</option>`).join('')}</select>${weekdayPicker('task-weekdays',t)}<label class="checkline"><input id="task-fixed" type="checkbox" ${t?.fixed_time?'checked':''}> Mantener este horario fijo al reajustar</label><label for="task-notes">Nota o resultado esperado</label><textarea id="task-notes" rows="3" maxlength="4000">${esc(t?.notes||'')}</textarea><div class="row-actions">${btn('save-task','Guardar tarea','check','primary','type="submit"')}</div><p id="task-error" class="form-error" role="alert"></p></form>`);$('task-form').onsubmit=e=>{e.preventDefault();saveTask(t);};}
async function saveTask(t){try{const day=$('task-day').value;const item=parsePlan(JSON.stringify([{start:$('task-start').value,end:$('task-end').value,title:$('task-title').value,category:$('task-category').value,priority:$('task-priority').value,notes:$('task-notes').value,recurrence:recurrenceFor(selectedDays('task-weekdays')),recurrence_days:selectedDays('task-weekdays'),fixed_time:$('task-fixed').checked}]),day)[0];await mutation(async()=>{await rpc('ritmo_save_task',{task_id:t?.id||null,item});toast('Tarea guardada.');});}catch(error){$('task-error').textContent=errorMessage(error);}}
function timeEnd(start,minutes){return new Date(new Date(start).getTime()+minutes*60000).toISOString();}
async function saveCarry(t){const start=madridTime($('carry-day').value,$('carry-time').value),end=timeEnd(start,Number($('carry-duration').value));await mutation(async()=>{await rpc('ritmo_reschedule_task',{task_id:t.id,new_start:start,new_end:end});toast('Nuevo bloque guardado.');});}
async function saveReview(){const r=reviewState,review=$('review-note').value,finishMode=document.querySelector('input[name="finish-mode"]:checked')?.value||'keep';if(r.mode==='continued'&&document.querySelector('input[name="continue-kind"]:checked')?.value!=='park'){const kind=document.querySelector('input[name="continue-kind"]:checked').value,minutes=Number($('continue-minutes').value),day=$('continue-day').value;if(!day||!Number.isInteger(minutes)||minutes<5||minutes>720){toast('Elige el día y entre 5 y 720 minutos para retomarla.');return;}const request={task_id:r.task.id,minutes,plan_day:day,automatic:kind==='auto',starts_at:kind==='manual'?madridTime(day,$('continue-time').value):null,review_text:review,score:r.rating,finish_mode:finishMode};state.busy=true;try{const p=await rpc('ritmo_continue',{request:{...request,apply:false}});pendingAdapt=request;pendingRpc='ritmo_continue';modal(`${modalHeader('Tu continuación ya tiene horario')}<div class="notice">Retomarás este bloque el ${esc(dayLabel(p.plan_day))}, a las ${timeLabel(p.starts_at)}. Volverás a recibir sus avisos.</div>${adjustmentList(p.changes)}<div class="row-actions">${btn('apply-adapt','Guardar decisión y horario','check','primary')}${btn('close-modal','Cancelar')}</div>`);}finally{state.busy=false;}return;}let start=null,end=null;if(r.mode==='postponed'){if(!$('review-day').value||!$('review-time').value){toast('Elige día y hora para el nuevo bloque.');return;}start=madridTime($('review-day').value,$('review-time').value);end=timeEnd(start,goalDuration(r.task));}await previewAdapt({action:'close',task_id:r.task.id,outcome:r.mode,review_text:review,score:r.rating,new_start:start,new_end:end,finish_mode:finishMode},r.mode==='continued'?'Dejar pendiente, sin horario ni aviso':finishMode==='advance'?'Terminar y adelantar el día':'Cerrar el bloque y revisar el día');}
let planPreview;
function previewPlan(){try{const day=$('plan-date').value;if(!day)throw new Error('Elige el día del plan.');planPreview={day,tasks:parsePlan($('plan-text').value,day)};const existing=state.tasks.filter(t=>dateKey(new Date(t.starts_at))===day);if(existing.some(t=>t.status!=='pending'))throw new Error('Este día ya tiene bloques empezados o revisados. Edítalos desde la agenda para conservar su registro.');modal(`${modalHeader('Así queda tu día')}<p class="modal-detail">${esc(dayLabel(day))} · ${planPreview.tasks.length} bloques</p>${existing.length?'<div class="notice">Se actualizarán los bloques incluidos con su referencia. Las tareas pendientes que omitas pasarán a la papelera. Los demás días se conservan.</div>':''}<div class="preview-list">${planPreview.tasks.map(t=>`<div class="preview-item"><strong>${timeLabel(t.starts_at)}–${timeLabel(t.ends_at)}</strong><span>${esc(t.title)}<br><small class="muted">${CATEGORIES[t.category]} · ${t.priority} · ${formatDuration(duration(t))}</small></span></div>`).join('')}</div><div class="row-actions">${btn('save-plan','Guardar este plan','check','primary')}${btn('close-modal','Volver a editar')}</div>`);}catch(error){$('plan-error').textContent=errorMessage(error);}}
function base64Bytes(str){return Uint8Array.from(atob(str.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-str.length%4)%4)),c=>c.charCodeAt(0));}
function pushEnvironment(){
  return {isIOS:/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1),standalone:navigator.standalone===true||window.matchMedia('(display-mode: standalone)').matches,serviceWorker:'serviceWorker'in navigator,notification:'Notification'in window,pushManager:'PushManager'in window};
}
function pushSupport(registration){return notificationSupport(pushEnvironment(),registration);}
async function pushRegistration(){
  const support=pushSupport();if(!support.supported)throw new Error(support.message);
  let timer;try{serviceWorker=await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('No se pudieron preparar los avisos. Recarga Ritmo y vuelve a intentarlo.')),8000);})]);}finally{clearTimeout(timer);}
  const available=pushSupport(serviceWorker);if(!available.supported)throw new Error(available.message);
  return serviceWorker;
}
async function enablePush(){
  const support=pushSupport();if(!support.supported){toast(support.message);return;}
  if(!config.vapidPublicKey){toast('Los avisos aún necesitan completar su configuración.');return;}
  try{
    const permission=await Notification.requestPermission();
    if(permission!=='granted'){toast('Activa el permiso de notificaciones para Ritmo en los ajustes del iPhone o del navegador.');return;}
    const registration=await pushRegistration();let sub=await registration.pushManager.getSubscription();
    if(!sub)sub=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64Bytes(config.vapidPublicKey)});
    const {error}=await db.from('ritmo_push_subscriptions').upsert({user_id:state.user.id,endpoint:sub.endpoint,subscription:sub.toJSON(),device_label:navigator.userAgent.slice(0,200)},{onConflict:'user_id,endpoint'});if(error)throw error;
    await rpc('ritmo_set_notifications',{enabled:true});toast('Avisos activados. Envía una prueba para comprobarlos.');await load();
  }catch(error){toast(errorMessage(error));}
}
async function testPush(){
  try{
    const registration=await pushRegistration();
    if(Notification.permission!=='granted'){toast('Activa primero los avisos en este dispositivo.');return;}
    const sub=await registration.pushManager.getSubscription();if(!sub){toast('Activa primero los avisos en este dispositivo.');return;}
    const {error}=await db.functions.invoke('ritmo-push',{body:{action:'test',endpoint:sub.endpoint}});
    if(error){
      const status=error.context?.status;
      throw new Error(status===401?'Tu sesión ha caducado. Vuelve a entrar para enviar la prueba.':status===404?'Activa de nuevo los avisos en este dispositivo.':status===429?'Espera un minuto antes de enviar otra prueba.':'No se pudo enviar la prueba. Comprueba Internet y vuelve a intentarlo.');
    }
    toast('Prueba enviada. Comprueba las notificaciones del móvil.');
  }catch(error){toast(errorMessage(error));}
}

async function install(){if(installPrompt){await installPrompt.prompt();installPrompt=null;return;}modal(`${modalHeader('Lleva Ritmo contigo')}<p class="modal-detail"><strong>En iPhone</strong><br>Abre esta dirección en Safari. Pulsa Compartir y «Añadir a pantalla de inicio». Abre la app desde el nuevo icono y activa los avisos en Ajustes.</p><p class="modal-detail"><strong>En Android</strong><br>Abre esta dirección en Chrome. En el menú pulsa «Instalar aplicación» o «Añadir a pantalla de inicio». Después permite las notificaciones.</p><div class="notice">La primera vez tendrás que iniciar sesión. La sesión se mantiene en este dispositivo hasta que la cierres.</div>${btn('close-modal','Entendido','','primary')}`);}
async function copyText(text,message){try{await navigator.clipboard.writeText(text);toast(message);}catch{modal(`${modalHeader('Texto para ChatGPT')}<textarea id="summary-copy" rows="14" readonly>${esc(text)}</textarea><p class="intro">Selecciona el texto y cópialo.</p>`);$('summary-copy').select();}}
async function copySummary(){await copyText(chatSummary(state.tasks,state.date),'Balance del día copiado, con tu historial de repeticiones.');}
function targetPlanDay(){const day=$('plan-date')?.value||planningDay;if(!day)throw new Error('Elige el día que vamos a preparar.');return day;}
async function copyChat(part){const day=targetPlanDay();const text=part==='instructions'?planInstructions(day):part==='balance'?chatSummary(state.tasks,state.date):part==='agenda'?agendaContext(state.tasks,state.date,day):allForChat(state.tasks,state.date,day);await copyText(text,part?'Parte copiada para ChatGPT.':'Todo copiado. Pégalo en ChatGPT y añade tus nuevas tareas.');}
function routinePreview(){const day=targetPlanDay();if(day<=state.date||day<dateKey())throw new Error('Elige un día futuro posterior al día del balance.');modal(`${modalHeader('Programar tu rutina')}<p class="modal-detail">Añadirás los bloques de rutina del ${esc(dayLabel(day))}. Las tareas que ya estén programadas se conservan; no se colocarán bloques en horas ocupadas.</p><div class="row-actions">${btn('confirm-routine','Programar en la agenda','calendar','primary',`data-day="${day}"`)}${btn('close-modal','Cancelar')}</div>`);}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,t=getTask(b.dataset.id);if(calendarState&&['start','adjust-day','organize-focus','repeat-task','delete-task','confirm-delete','swipe-delete','trash','restore-task','review','save-review','schedule-carry','new-task','edit-task','save-plan','schedule-routine','confirm-routine','logout'].includes(action)){toast('Guarda o cancela tu propuesta del calendario antes de cambiar otra tarea.');return;}if(b.type==='submit'&&['login','save-task','save-carry','save-password','save-repeat'].includes(action))return;try{switch(action){
case 'login-mode':if(!state.busy)renderLogin(b.dataset.mode);break;
case 'request-link':await requestLoginLink(b);break;
case 'password-setup':passwordModal();break;
case 'navigate':if(calendarState){toast('Guarda o cancela tu propuesta del calendario antes de salir.');break;}state.view=b.dataset.view;if(state.view==='planning'&&!planningText)planningDay=addDays(state.date);state.error=null;render();window.scrollTo(0,0);break;
case 'filter':state.filter=b.dataset.filter;render();break;
case 'previous-day':if(calendarState){toast('Guarda o cancela tu propuesta antes de cambiar de día.');break;}state.date=addDays(state.date,-1);render();break;
case 'next-day':if(calendarState){toast('Guarda o cancela tu propuesta antes de cambiar de día.');break;}state.date=addDays(state.date);render();break;
case 'refresh':await load();break;
case 'close-modal':closeModal();break;
case 'start':await startTask(t);break;
case 'adjust-day':adjustDayModal();break;
case 'organize-focus':adjustDayModal(t?.id);break;
case 'back-organizer':renderOrganizer();break;
case 'organize-up':organizerMove(b.dataset.id,-1);break;
case 'organize-down':organizerMove(b.dataset.id,1);break;
case 'organize-now':collectOrganizer();organizerState.start=timeLabel(soon());$('organizer-start').value=organizerState.start;break;
case 'organize-no-cooking':{collectOrganizer();const meal=organizerNoCooking(organizerState.items,state.tasks);if(!meal){toast('Puedes reducir el bloque de comida directamente en la lista.');break;}Object.assign(organizerState.items.find(t=>t.id===meal.id),meal);$('organizer-items').innerHTML=organizerRows();toast('Dejo '+meal.minutes+' minutos para comer y descansar hoy. Puedes ajustarlos.');break;}
case 'preview-organizer':await previewOrganizer();break;
case 'preview-shift-now':await previewAdapt({action:'shift',plan_day:state.date,from_now:true});break;
case 'preview-shift':{const minutes=Number($('shift-minutes').value);if(!Number.isInteger(minutes)||minutes<1||minutes>720){toast('Elige de 1 a 720 minutos.');break;}await previewAdapt({action:'shift',plan_day:state.date,offset_minutes:minutes});break;}
case 'apply-adapt':await mutation(async()=>{const result=await rpc(pendingRpc,{request:{...pendingAdapt,apply:true}});if(pendingRpc==='ritmo_calendar'){calendarState=null;toast('Calendario guardado. Los avisos siguen tus nuevos horarios.');}else if(pendingRpc==='ritmo_reorganize'){state.view='today';state.date=pendingAdapt.plan_day;toast(`Agenda guardada: ${result.restored} tareas recuperadas; ${result.unplaced} por recolocar.`);}else if(pendingRpc==='ritmo_continue'){state.view='today';toast('Continuación guardada para las '+timeLabel(result.starts_at)+'. Recibirás sus avisos.');}else toast(pendingAdapt.action==='start'?'Tarea en curso. Agenda reajustada.':pendingAdapt.outcome==='continued'?'Queda pendiente sin aviso. Puedes retomarla desde Reorganizar mi día.':'Decisión guardada. Tu objetivo y tu tiempo real quedan registrados.');});break;
case 'repeat-preset':{const days=b.dataset.days==='all'?[1,2,3,4,5,6,7]:b.dataset.days==='work'?[1,2,3,4,5]:[];$(b.dataset.picker).querySelectorAll('input').forEach(input=>input.checked=days.includes(Number(input.value)));break;}
case 'calendar-zoom':{const viewport=$('calendar-scroll'),center=viewport?(viewport.scrollTop+viewport.clientHeight/2)/calendarScale():0;state.calendarZoom=b.dataset.mode;refreshCalendar();$('calendar-scroll').scrollTop=center*calendarScale()-$('calendar-scroll').clientHeight/2;break;}
case 'day-view':if(calendarState){toast('Guarda o cancela tu propuesta antes de cambiar de vista.');break;}state.dayView=b.dataset.mode;render();scrollCalendar();break;
case 'calendar-edit':beginCalendar();break;
case 'calendar-cancel':calendarState=null;render();scrollCalendar();break;
case 'calendar-edit-block':calendarBlockModal(b.dataset.id);break;
case 'calendar-update-block':calendarUpdate(b.dataset.id);break;
case 'calendar-unplace':calendarState.items.find(i=>i.id===b.dataset.id).placed=false;closeModal();refreshCalendar();break;
case 'calendar-preview':await previewCalendar();break;
case 'repeat-task':repeatModal(t,Number(b.dataset.minutes)||null);break;
case 'detail':detailModal(t);break;
case 'swipe-delete':if(state.busy||!t||!['pending','deferred'].includes(t.status))break;b.disabled=true;try{await deleteTask(t,{quick:true});}finally{if(b.isConnected)b.disabled=false;}break;
case 'delete-task':deleteTaskModal(t);break;
case 'confirm-delete':await deleteTask(t);break;
case 'trash':await trashModal();break;
case 'restore-task':await mutation(async()=>{const restored=await rpc('ritmo_restore_task',{task_id:b.dataset.id});toast(['deferred','continued'].includes(restored.status)?'Tarea recuperada. Usa Reorganizar mi día para darle un horario.':'Tarea recuperada.');});break;
case 'review':reviewModal(t,b.dataset.mode||'completed');break;
case 'review-mode':reviewState.mode=b.dataset.mode;document.querySelectorAll('.review-options button').forEach(el=>el.classList.toggle('active',el.dataset.mode===reviewState.mode));$('review-schedule').innerHTML=reviewSchedule();break;
case 'rate':reviewState.rating=Number(b.dataset.rating);document.querySelectorAll('.rating-row button').forEach(el=>el.classList.toggle('active',Number(el.dataset.rating)===reviewState.rating));break;
case 'save-review':await saveReview();break;
case 'schedule-carry':scheduleModal(t);break;
case 'new-task':editModal();break;
case 'edit-task':editModal(t);break;
case 'copy-summary':await copySummary();break;
case 'preview-plan':previewPlan();break;
case 'save-plan':await mutation(async()=>{await rpc('ritmo_import_plan',{plan_day:planPreview.day,items:planPreview.tasks});state.date=planPreview.day;state.view='today';planningText='';toast('Tu plan está guardado. Un paso a la vez.');});break;
case 'copy-chat-all':await copyChat();break;
case 'copy-chat-part':await copyChat(b.dataset.part);break;
case 'schedule-routine':routinePreview();break;
case 'confirm-routine':await mutation(async()=>{const count=await rpc('ritmo_copy_routine',{from_day:state.date,to_day:b.dataset.day});toast(count?`${count} tareas de rutina programadas para ${b.dataset.day}.`:'No se añadieron bloques: no corresponde ninguna rutina, ya está programada o sus horas están ocupadas. Puedes organizar el día manualmente.');});break;
case 'enable-push':b.disabled=true;await enablePush();if(b.isConnected)b.disabled=false;break;
case 'test-push':b.disabled=true;await testPush();if(b.isConnected)b.disabled=false;break;
case 'disable-push':await mutation(async()=>{await rpc('ritmo_set_notifications',{enabled:false});toast('Recordatorios pausados en todos tus dispositivos.');});break;
case 'install':await install();break;
case 'logout':await db.auth.signOut({scope:'local'});state.user=null;state.tasks=[];state.health=null;renderLogin();break;
case 'export-data':{const blob=new Blob([JSON.stringify({exported_at:new Date().toISOString(),timezone:config.timezone,tasks:state.tasks},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ritmo-${state.date}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break;}
}}catch(error){toast(errorMessage(error));if(b.isConnected)b.disabled=false;}});
document.addEventListener('input',e=>{if(e.target.id==='plan-text')planningText=e.target.value;if(e.target.id==='plan-date')planningDay=e.target.value;});
document.addEventListener('change',e=>{if(e.target.id==='plan-date')planningDay=e.target.value;if(e.target.matches('input[name="continue-kind"]')){const park=e.target.value==='park';$('continue-fields').hidden=park;$('continue-time-label').hidden=e.target.value!=='manual';$('continue-explanation').textContent=park?'Sin horario no habrá recordatorio. La verás en las tareas por recolocar.':'Guardaremos un nuevo bloque para que vuelvas a recibir avisos cuando toque retomarlo.';}if(e.target.classList.contains('org-fixed')){collectOrganizer();e.target.closest('.organize-row').querySelector('.org-time').parentElement.hidden=!e.target.checked;}if(e.target.id==='task-category'&&$('task-fixed'))$('task-fixed').checked=['work','meals'].includes(e.target.value);if(e.target.id==='agenda-date'&&e.target.value){if(calendarState){e.target.value=state.date;toast('Guarda o cancela tu propuesta antes de cambiar de día.');return;}state.date=e.target.value;render();}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
window.addEventListener('online',()=>{if(state.user)load();});window.addEventListener('offline',()=>render());
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.user&&!$('modal').open)load();});
$('modal').addEventListener('close',()=>{const form=$('password-form');if(form)form.reset();});
$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const rect=$('modal').getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)closeModal();}});
async function init(){
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(r=>serviceWorker=r).catch(()=>{});
  if(!config.supabaseUrl||!config.supabaseKey){$('app').innerHTML='<div class="boot"><span class="brand-icon">r.</span><h2>Tu espacio está casi listo</h2><p>Falta conectar tu cuenta. Conserva esta página y vuelve cuando termine la configuración.</p></div>';return;}
  for(let i=0;i<50&&!window.supabase;i++)await new Promise(r=>setTimeout(r,100));
  if(!window.supabase){$('app').innerHTML='<div class="boot"><h2>No se pudo abrir tu agenda</h2><p>Comprueba tu conexión y vuelve a cargar la página.</p></div>';return;}
  db=window.supabase.createClient(config.supabaseUrl,config.supabaseKey);
  db.auth.onAuthStateChange((event,session)=>{const changed=state.user?.id!==session?.user?.id;state.user=session?.user||null;if(changed){if(state.user){state.loading=true;render();setTimeout(()=>load(true),0);}else{state.tasks=[];renderLogin();}}});
  const {data:{session},error}=await db.auth.getSession();if(error)toast(errorMessage(error));state.user=session?.user||null;if(state.user)await load(true);else renderLogin();
  refreshTimer=setInterval(()=>{if(state.user&&!calendarState&&!document.hidden&&!state.busy&&!$('modal').open&&!document.querySelector('#plan-text:focus, #plan-date:focus')&&state.view!=='planning')load();},45000);
  clockTimer=setInterval(()=>{if(state.user&&state.view==='today'&&!$('modal').open&&!state.busy){if(state.dayView==='calendar'){const now=$('calendar-now');if(now&&state.date===dateKey()){now.style.top=clockMinutes(new Date())*calendarScale()+'px';now.querySelector('span').textContent=timeLabel(new Date());}return;}const active=document.activeElement;if(active?.tagName!=='INPUT')render();}},60000);
}
bindTaskSwipes();
bindCalendarGestures({getScale:calendarScale,getDraft:()=>calendarState,onChange:refreshCalendar,onMessage:message=>{calendarMessage(message);}});
init();
