import {config} from './config.js';
import {CLOSED,CATEGORIES,STATUS,escapeHtml as esc,dateKey,addDays,madridTime,timeLabel,dayLabel,duration,currentTask,parsePlan,summaryText} from './domain.js';
const paths={home:'<path d="M3 10l9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18m-12 5h2m4 0h2"/>',plan:'<path d="M12 3v18M3 12h18"/>',chart:'<path d="M4 20h16M6 16V9m6 7V4m6 12v-5"/>',settings:'<path d="M12 3v3m0 12v3M3 12h3m12 0h3M5.6 5.6l2.1 2.1m8.6 8.6 2.1 2.1m0-12.8-2.1 2.1m-8.6 8.6-2.1 2.1"/><circle cx="12" cy="12" r="5"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',check:'<path d="m5 12 4 4L19 6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',play:'<path d="m8 4 12 8-12 8z"/>',edit:'<path d="m16 3 5 5-13 13H3v-5zM14 5l5 5"/>',back:'<path d="m14 6-6 6 6 6"/>',next:'<path d="m10 6 6 6-6 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',logout:'<path d="M9 3H3v18h6m6-16 7 7-7 7m-8-7h15"/>',spark:'<path d="m12 3 2.7 6.3L21 12l-6.3 2.7L12 21l-2.7-6.3L3 12l6.3-2.7z"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.clock}</svg>`;
const nav=[['today','home','Mi día'],['planning','calendar','Preparar mañana'],['balance','chart','Mi balance'],['settings','settings','Ajustes']];
const state={user:null,tasks:[],date:dateKey(),view:'today',filter:'all',loading:true,busy:false,notifications:false,health:null,error:null};
let db,serviceWorker,refreshTimer,clockTimer,installPrompt;
const $=id=>document.getElementById(id);
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),5500);}
const btn=(action,text,ic='',classes='',attrs='')=>`<button class="btn ${classes}" data-action="${action}" ${attrs}>${ic?icon(ic):''}${text}</button>`;
function modal(html){$('modal-body').innerHTML=html;$('modal').showModal();}
const modalHeader=title=>`<div class="modal-header"><h2>${esc(title)}</h2>${btn('close-modal','<span class="sr-only">Cerrar</span>','close','icon-only','aria-label="Cerrar"')}</div>`;
function closeModal(){if($('modal').open)$('modal').close();}
function errorMessage(error){const msg=error?.message||String(error);if(/Invalid login credentials/.test(msg))return 'El correo o la contraseña no coinciden. Revisa tus datos.';if(/rate limit|too many/i.test(msg))return 'Se han enviado demasiadas solicitudes. Espera antes de solicitar otro enlace; el servicio limita los envíos.';if(/fetch|network/i.test(msg))return 'No se pudo conectar. Comprueba Internet y vuelve a intentarlo.';if(/not authorized|forbidden|owner/i.test(msg))return 'Esta cuenta no tiene acceso a tu agenda personal.';return msg;}
function renderLogin(){
  $('app').innerHTML=`<main class="login"><section class="login-story"><div><div class="brand"><span class="brand-icon">r.</span>ritmo</div><h1>Un día con intención.<br><span>Una tarea a la vez.</span></h1><p>Un lugar para ordenar tu día, hacer espacio para lo que importa y volver a empezar cuando haga falta.</p><div class="login-feature"><span>${icon('calendar')}Tu agenda</span><span>${icon('bell')}Tus recordatorios</span><span>${icon('check')}Tu progreso</span></div></div><div class="login-story-footer">Tu espacio personal. Sin ruido.</div></section><section class="login-form"><div><div class="eyebrow">Bienvenida a tu espacio</div><h2>Vamos a por tu día</h2><p class="intro">Entra con tu cuenta personal para abrir tu agenda.</p><form id="login-form"><label for="email">Correo electrónico</label><input id="email" name="email" type="email" autocomplete="username" required placeholder="Tu correo"><div id="otp-area" hidden><label for="otp">Enlace de tu correo</label><input id="otp" name="otp" type="url" autocomplete="off" disabled placeholder="Pega aquí el enlace de acceso"><p class="hint">En el correo, mantén pulsado «Sign in», copia su enlace y pégalo aquí. También puedes abrirlo directamente en Safari.</p><button type="button" class="text-btn" data-action="reset-login">Cambiar correo</button></div>${btn('login','Recibir mi enlace de acceso','','primary','type="submit"')}<p id="login-error" class="form-error" role="alert"></p></form><div class="divider"></div>${btn('magic-link','Volver a enviar el enlace','copy','subtle','hidden')}<p class="hint">Tu agenda solo admite tu correo autorizado. El enlace también sirve desde la app instalada en tu iPhone; la sesión se mantiene abierta.</p></div></section></main>`;
  $('login-form').onsubmit=async e=>{e.preventDefault();if(state.busy)return;state.busy=true;const b=e.submitter;b.disabled=true;$('login-error').textContent='';try{const email=$('email').value.trim();if($('otp-area').hidden){const {error}=await db.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:new URL('./',location.href).href}});if(error)throw error;$('otp-area').hidden=false;$('otp').disabled=false;$('otp').required=true;$('email').readOnly=true;document.querySelector('[data-action="magic-link"]').hidden=false;b.textContent='Entrar a mi agenda';$('otp').focus();toast('Revisa tu correo. Copia el enlace y pégalo aquí.');}else{let link;try{link=new URL($('otp').value.trim());}catch{throw new Error('Copia el enlace completo del botón Sign in de tu correo.');}if(link.origin!==new URL(config.supabaseUrl).origin||link.pathname!=='/auth/v1/verify'||link.searchParams.get('type')!=='magiclink')throw new Error('Este enlace no pertenece a tu cuenta de Ritmo. Solicita uno nuevo.');const token=link.searchParams.get('token')||link.searchParams.get('token_hash');if(!token)throw new Error('El enlace está incompleto. Cópialo de nuevo desde el correo.');const {error}=await db.auth.verifyOtp({token_hash:token,type:'magiclink'});if(error)throw error;}}catch(error){$('login-error').textContent=errorMessage(error);}finally{state.busy=false;if(b.isConnected)b.disabled=false;}};
}
function todayTasks(){return state.tasks.filter(t=>dateKey(new Date(t.starts_at))===state.date).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));}
function summary(tasks){return {done:tasks.filter(t=>t.status==='completed').length,closed:tasks.filter(t=>CLOSED.includes(t.status)).length,total:tasks.length,minutes:tasks.filter(t=>t.status==='completed').reduce((n,t)=>n+duration(t),0)};}
function navHtml(mobile=false){return nav.map(([id,ic,label])=>`<button class="${mobile?'':'nav-btn '}${state.view===id?'active':''}" data-action="navigate" data-view="${id}" ${state.view===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span></button>`).join('');}
function render(){
  if(!state.user){renderLogin();return;}
  const heading={today:state.date===dateKey()?'Tu día, en orden':state.date===addDays(dateKey())?'Mañana, en orden':'Tu agenda',planning:'Haz espacio para mañana',balance:'Cada paso cuenta',settings:'A tu manera'}[state.view];
  $('app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-icon">r.</span>ritmo</div><nav aria-label="Navegación principal">${navHtml()}</nav><div class="sidebar-bottom"><p class="sidebar-note">No necesitas hacerlo todo.<br>Solo dar el siguiente paso.</p><div class="profile"><span class="avatar">N</span><div>Nicole<small>Mi espacio personal</small></div></div></div></aside><main class="main"><div class="mobile-brand"><div class="brand"><span class="brand-icon">r.</span>ritmo</div><span class="sync-status">${state.loading?'Sincronizando…':navigator.onLine?'Mi espacio personal':'Sin conexión'}</span></div><header class="topbar"><div><div class="eyebrow">${state.view==='today'?'Una cosa a la vez':'Mi espacio personal'}</div><h1>${heading}</h1><p class="date-line">${esc(dayLabel(state.date))}</p></div><div class="top-actions">${btn('navigate','<span>Preparar mañana</span>','calendar','', 'data-view="planning" aria-label="Preparar mañana"')}${btn('navigate','','bell','icon-only','data-view="settings" aria-label="Ajustes de notificaciones"')}</div></header>${!navigator.onLine?'<div class="offline-banner">Sin conexión. Puedes revisar lo que ya está cargado; conecta Internet para guardar cambios.</div>':''}${state.error?`<div class="notice error" role="alert">${esc(state.error)} ${btn('refresh','Reintentar')}</div>`:''}${state.loading&&!state.tasks.length?'<div class="empty">Cargando tu agenda…</div>':({today:renderToday,planning:renderPlanning,balance:renderBalance,settings:renderSettings}[state.view])()}<p class="sync-line">Europe/Madrid · ${state.loading?'Sincronizando…':'Los cambios se guardan en tu cuenta'}</p></main><nav class="mobile-nav" aria-label="Navegación móvil">${navHtml(true)}</nav></div>`;
}
function focusCard(tasks){
  const t=currentTask(tasks), now=new Date();if(!t)return `<section class="focus-card"><div class="focus-top"><span class="focus-label">${icon('spark')} ESPACIO PARA TI</span></div><h2>${tasks.length?'Tu agenda está revisada.':'Tu día empieza aquí.'}</h2><p class="focus-note">${tasks.length?'Has cerrado todos los bloques de este día. Revisa el balance y prepara el siguiente.':'Pega el plan que preparemos en el chat. Antes de guardarlo podrás revisar los horarios.'}</p><div class="row-actions">${btn('navigate','Preparar el plan','calendar','lime','data-view="planning"')}</div></section>`;
  const future=new Date(t.starts_at)>now, active=t.status==='active', overdue=active&&new Date(t.ends_at)<now;
  const remaining=Math.max(0,Math.ceil((new Date(active?t.ends_at:t.starts_at)-now)/60000));
  const label=overdue?'ES MOMENTO DE CAMBIAR':active?'AHORA, TU FOCO':future?'TU SIGUIENTE PASO':'PUEDES EMPEZAR AQUÍ';
  return `<section class="focus-card"><div class="focus-top"><span class="focus-label">${icon('spark')} ${label}</span><span class="focus-category">${CATEGORIES[t.category]}</span></div><h2>${esc(t.title)}</h2>${t.notes?`<p class="focus-note">${esc(t.notes)}</p>`:''}<div class="focus-time"><strong>${active&&!overdue?remaining+'<small style="font-size:1rem;letter-spacing:0"> min</small>':timeLabel(t.starts_at)}</strong><span>${active&&!overdue?'para el siguiente bloque':`${timeLabel(t.ends_at)} · ${duration(t)} min`}</span></div><div class="focus-actions">${active?btn('review','Terminar bloque','check','lime',`data-id="${t.id}"`):btn('start','Empezar tarea','play','lime',`data-id="${t.id}"`)}${btn('review','Reprogramar','calendar','subtle',`data-id="${t.id}" data-mode="continued"`)}</div><div class="focus-footer">${icon('clock')} ${overdue?'Cierra este bloque para dar el siguiente paso.':future?'Aún tienes tiempo. Tu próximo paso ya está preparado.':'Tu progreso se mide en pasos, no en perfección.'}</div></section>`;
}
function taskRows(tasks){return tasks.map(t=>`<article class="task-row category-${t.category} ${t.status==='active'?'current':''} ${CLOSED.includes(t.status)?'closed':''}"><div class="task-time">${timeLabel(t.starts_at)}<small>${timeLabel(t.ends_at)}</small></div><div class="task-info"><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span>${CATEGORIES[t.category]}</span><span>·</span><span>${duration(t)} min</span>${t.priority==='alta'?'<span>· Prioridad alta</span>':''}${t.recurrence==='daily'?'<span>· Diaria</span>':''}<span class="task-status">${STATUS[t.status]}</span></div></div><button class="task-open" data-action="detail" data-id="${t.id}" aria-label="Ver ${esc(t.title)}">${icon(CLOSED.includes(t.status)?'check':t.status==='active'?'clock':'edit')}</button></article>`).join('');}
function renderToday(){
  const tasks=todayTasks(),s=summary(tasks),priorities=tasks.filter(t=>t.priority==='alta'&&!CLOSED.includes(t.status)).slice(0,3);
  const filtered=tasks.filter(t=>state.filter==='all'||(state.filter==='open'?!CLOSED.includes(t.status):CLOSED.includes(t.status)));
  return `<div class="layout"><div>${focusCard(tasks)}<div class="section-head"><h2>Tu agenda</h2><div class="date-control">${btn('previous-day','','back','icon-only','aria-label="Día anterior"')}<input type="date" id="agenda-date" value="${state.date}" aria-label="Fecha de la agenda">${btn('next-day','','next','icon-only','aria-label="Día siguiente"')}${btn('new-task','Añadir','plan')}</div></div><div class="segmented" role="group" aria-label="Filtrar tareas">${[['all','Todas'],['open','Por hacer'],['closed','Revisadas']].map(([f,l])=>`<button class="${state.filter===f?'active':''}" data-action="filter" data-filter="${f}">${l}</button>`).join('')}</div><div class="task-list">${filtered.length?taskRows(filtered):'<div class="empty">'+(tasks.length?'No hay tareas en este filtro.':'Este día aún tiene la agenda vacía.')+'</div>'}</div></div><aside class="right-stack"><section class="card progress-card"><h2>Un paso más cerca</h2><div class="progress-ring" style="--progress:${s.total?s.done/s.total*100:0}%"><div class="progress-number">${s.done}<small>de ${s.total} completadas</small></div></div><p class="progress-caption">${s.total===0?'Prepara tu primer día.':s.done===s.total?'Has cumplido lo que te propusiste.':'Cada bloque cuenta.'}</p><div class="mini-stats"><div><strong>${Math.floor(s.minutes/60)}h ${s.minutes%60}m</strong><span>Tiempo planificado cumplido</span></div><div><strong>${s.closed}</strong><span>Bloques revisados</span></div></div></section><section class="card"><h2>Lo que importa hoy</h2><div class="priority-list">${priorities.length?priorities.map((t,i)=>`<div class="priority-item"><span class="priority-mark">0${i+1}</span><div><strong>${esc(t.title)}</strong><small>${timeLabel(t.starts_at)} · ${CATEGORIES[t.category]}</small></div></div>`).join(''):'<p class="muted" style="font-size:.9rem;line-height:1.6">Tus prioridades están al día. Puedes revisar el balance.</p>'}</div></section><section class="card notification-card"><h2>${icon('bell')} Un pequeño empujón</h2><p>${state.notifications?'Avisos 2 minutos antes, al empezar y cada 5 minutos hasta que revises o empieces el bloque pendiente.':'Activa los avisos en tu móvil para recordar cada cambio de tarea, incluso con la app cerrada.'}</p>${btn('navigate',state.notifications?'Revisar mis avisos':'Configurar mis avisos','bell','','data-view="settings"')}</section></aside></div>`;
}
function carryTasks(){const linked=new Set(state.tasks.filter(t=>!CLOSED.includes(t.status)).map(t=>t.source_task_id).filter(Boolean));return state.tasks.filter(t=>dateKey(new Date(t.starts_at))<=state.date&&['pending','active','continued','postponed'].includes(t.status)&&!linked.has(t.id)).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));}
function renderPlanning(){const next=addDays(state.date),carry=carryTasks();return `<section class="card page-card"><div class="eyebrow">Cerrar hoy · preparar mañana</div><h2>Tu próxima agenda empieza en el chat</h2><p class="intro">Copia tu resumen, cuéntame qué necesitas hacer y te devolveré un plan para pegar aquí. Lo que queda pendiente también cuenta.</p><div class="row-actions">${btn('copy-summary','Copiar resumen para el chat','copy','primary')}${btn('copy-routine','Copiar rutina al día siguiente','calendar')}</div><div class="notice">El resumen incluye el estado y tus notas. Las tareas diarias se pueden copiar a mañana sin duplicar las ya programadas.</div><label for="plan-date">Día que vamos a preparar</label><input type="date" id="plan-date" value="${next}" required><label for="plan-text">Pega el plan del chat</label><textarea id="plan-text" rows="9" placeholder='{"tasks":[{"start":"07:00","end":"07:30","title":"Paseo","category":"personal","priority":"alta","notes":"Dejar el móvil en casa","recurrence":"daily"}]}'></textarea><p class="intro" style="font-size:.85rem;margin:10px 0">También acepta una tarea por línea: 07:00-07:30 | Paseo | personal | alta | Nota</p>${btn('preview-plan','Revisar antes de guardar','check','primary')}<p id="plan-error" role="alert" class="form-error"></p></section><div class="section-head"><h2>Para recuperar o continuar</h2><span class="muted">${carry.length} tareas</span></div><section class="card page-card carry-list">${carry.length?carry.map(t=>`<div class="carry-item"><div><strong>${esc(t.title)}</strong><p>${dayLabel(dateKey(new Date(t.starts_at)))} · ${STATUS[t.status]}${t.review?' · '+esc(t.review):''}</p></div>${btn('schedule-carry','Elegir otro momento','calendar','',`data-id="${t.id}"`)}</div>`).join(''):'<p class="muted">No tienes tareas por recuperar. Puedes preparar un día nuevo.</p>'}</section>`;}
function renderBalance(){const tasks=todayTasks(),s=summary(tasks);return `<section class="card page-card"><div class="section-head" style="margin-top:0"><h2>Así ha ido tu día</h2><input type="date" id="agenda-date" value="${state.date}" aria-label="Fecha del balance" style="max-width:170px"></div><p class="intro">Completar, continuar y reprogramar son decisiones. Aquí queda registrado lo que pasó.</p><div class="summary-stats"><div class="stat-block"><strong>${s.done}</strong><span>Completadas</span></div><div class="stat-block"><strong>${tasks.filter(t=>t.status==='continued').length}</strong><span>Continuaciones</span></div><div class="stat-block"><strong>${tasks.filter(t=>t.status==='postponed').length}</strong><span>Reprogramadas</span></div></div><div class="task-list">${taskRows(tasks)||'<div class="empty">No hay tareas este día.</div>'}</div><div class="row-actions">${btn('copy-summary','Copiar resumen del día','copy','primary')}${btn('export-data','Descargar mi registro','download')}</div></section>`;}
function renderSettings(){const permission='Notification'in window?Notification.permission:'unsupported';return `<section class="card page-card"><h2>Recordatorios que te acompañan</h2><p class="intro">Dos minutos antes de cada bloque, al empezar y cada cinco minutos si falta empezar o cerrar la tarea. Los avisos se detienen al tomar una decisión sobre ella.</p><div class="setting-row"><div><h3>Instalar en el móvil</h3><p>iPhone: Safari → Compartir → Añadir a pantalla de inicio. Después abre Ritmo desde el icono.<br>Android: menú del navegador → Instalar aplicación o Añadir a pantalla de inicio.</p></div>${btn('install','Cómo instalar','download')}</div><div class="setting-row"><div><h3>Avisos en este dispositivo</h3><p id="push-status">${permission==='denied'?'Permiso bloqueado. Activa las notificaciones en los ajustes del navegador o del móvil.':state.notifications?'Recordatorios activados en tu cuenta. Comprueba también este dispositivo.':'Activa los avisos desde el móvil en el que quieres recibirlos.'}</p></div>${btn('enable-push','Activar en este dispositivo','bell','primary')}</div><div class="setting-row"><div><h3>Comprobar los avisos</h3><p>Envía un aviso de prueba a este dispositivo y comprueba que aparece.</p></div>${btn('test-push','Enviar prueba','bell')}</div><div class="setting-row"><div><h3>Pausar los recordatorios</h3><p>Puedes silenciarlos en todos tus dispositivos y volver a activarlos cuando quieras.</p></div>${btn('disable-push','Pausar avisos','clock')}</div><div class="setting-row"><div><h3>Horario y privacidad</h3><p>Tu agenda usa la hora de Madrid y se guarda en tu cuenta. Los avisos de tareas se limitan al día en curso. Los datos de la agenda requieren iniciar sesión.</p></div></div>${state.health?`<p class="sync-line">Última comprobación de recordatorios: ${esc(new Date(state.health.checked_at).toLocaleString('es-ES',{timeZone:'Europe/Madrid'}))}</p>`:'<div class="notice">El envío depende de tu conexión, los permisos del móvil y sus modos de concentración. Los avisos pueden retrasarse.</div>'}<div class="setting-row"><div><h3>Tu sesión</h3><p>${esc(state.user.email)}</p></div>${btn('logout','Cerrar sesión','logout')}</div></section>`;}
async function load(initial=false){
  if(!state.user)return;state.loading=true;state.error=null;
  try{
    const owner=await db.from('ritmo_owners').select('user_id,notifications_enabled').eq('user_id',state.user.id).maybeSingle();if(owner.error)throw owner.error;if(!owner.data)throw new Error('Esta cuenta no tiene acceso a Ritmo. Usa el correo autorizado para esta agenda.');
    const {data,error}=await db.from('ritmo_tasks').select('*').order('starts_at');if(error)throw error;state.tasks=data;state.notifications=owner.data.notifications_enabled;
    if(initial&&!todayTasks().length){const next=state.tasks.find(t=>new Date(t.starts_at)>new Date());if(next)state.date=dateKey(new Date(next.starts_at));}
    const health=await db.from('ritmo_health').select('checked_at').eq('id',1).maybeSingle();if(!health.error)state.health=health.data;
  }catch(error){state.error=errorMessage(error);}finally{state.loading=false;render();}
}
async function mutation(fn){if(state.busy)return;if(!navigator.onLine){toast('Conecta Internet para guardar este cambio.');return;}state.busy=true;document.querySelectorAll('#modal button').forEach(b=>b.disabled=true);try{await fn();closeModal();await load();}catch(error){toast(errorMessage(error));}finally{state.busy=false;document.querySelectorAll('#modal button').forEach(b=>b.disabled=false);}}
function getTask(id){return state.tasks.find(t=>t.id===id);}
async function rpc(name,args){const {data,error}=await db.rpc(name,args);if(error)throw error;return data;}
async function startTask(t){const other=state.tasks.find(x=>x.status==='active'&&x.id!==t.id);if(other){toast('Cierra primero el bloque que sigue en curso.');reviewModal(other);return;}if(new Date(t.ends_at)<new Date()){toast('Este horario ya pasó. Elige otro momento para hacerla.');scheduleModal(t);return;}await mutation(async()=>{await rpc('ritmo_start_task',{task_id:t.id});toast('Un paso a la vez. Tarea en curso.');});}
function detailModal(t){modal(`${modalHeader(t.title)}<p class="modal-detail">${esc(dayLabel(dateKey(new Date(t.starts_at))))}<br>${timeLabel(t.starts_at)}–${timeLabel(t.ends_at)} · ${CATEGORIES[t.category]} · ${STATUS[t.status]}${t.recurrence==='daily'?'<br>Se repite cada día':''}</p>${t.notes?`<div class="notice">${esc(t.notes)}</div>`:''}${t.review?`<p class="modal-detail"><strong>Tu resultado:</strong> ${esc(t.review)}${t.rating?` · ${t.rating}/5`:''}</p>`:''}<div class="row-actions">${!CLOSED.includes(t.status)?`${t.status==='pending'?btn('start','Empezar','play','primary',`data-id="${t.id}"`):''}${btn('review','Evaluar bloque','check','',`data-id="${t.id}"`)}${btn('edit-task','Editar','edit','',`data-id="${t.id}"`)}`:btn('schedule-carry','Programar otro bloque','calendar','',`data-id="${t.id}"`)}</div>`);}
let reviewState;
function reviewModal(t,mode='completed'){reviewState={task:t,mode,rating:null};modal(`${modalHeader('¿Cómo ha ido el bloque?')}<p class="modal-detail">${esc(t.title)}</p><div class="review-options">${[['completed','check','La he terminado'],['continued','clock','Quiero continuar después'],['postponed','calendar','La paso a otro día'],['skipped','close','Ya no necesito hacerla']].map(([m,ic,label])=>btn('review-mode',label,ic,m===mode?'active':'',`data-mode="${m}"`)).join('')}</div><div id="review-schedule">${reviewSchedule()}</div><label for="review-note">¿Qué has conseguido o qué falta? <span class="muted">(opcional)</span></label><textarea id="review-note" rows="3" maxlength="4000" placeholder="Déjate una nota para retomar el hilo"></textarea><label>¿Cómo te has sentido? <span class="muted">(opcional)</span></label><div class="rating-row" aria-label="Valorar el bloque">${[1,2,3,4,5].map(n=>`<button data-action="rate" data-rating="${n}" aria-label="${n} de 5">${n}</button>`).join('')}</div><div class="row-actions">${btn('save-review','Guardar y dar el siguiente paso','check','primary')}</div>`);}
function reviewSchedule(){if(reviewState.mode!=='postponed')return reviewState.mode==='continued'?'<p class="intro" style="font-size:.88rem;margin:15px 0 0">Quedará en «Para recuperar o continuar». Después puedes elegir un nuevo horario.</p>':'';const t=reviewState.task;return `<div class="two-col"><div><label for="review-day">Nuevo día</label><input id="review-day" type="date" value="${addDays(dateKey(new Date(t.starts_at)))}"></div><div><label for="review-time">A qué hora</label><input id="review-time" type="time" value="${timeLabel(t.starts_at)}"></div></div>`;}
function scheduleModal(t){modal(`${modalHeader('Dale otro momento')}<p class="modal-detail">${esc(t.title)} · ${duration(t)} minutos</p><form id="schedule-form"><div class="two-col"><div><label for="carry-day">Día</label><input id="carry-day" type="date" required value="${addDays(state.date)}"></div><div><label for="carry-time">Hora de inicio</label><input id="carry-time" type="time" required value="${timeLabel(t.starts_at)}"></div></div><label for="carry-duration">Duración en minutos</label><input id="carry-duration" type="number" min="5" max="720" value="${duration(t)}" required><div class="row-actions">${btn('save-carry','Guardar nuevo bloque','calendar','primary',`data-id="${t.id}" type="submit"`)}</div></form>`);$('schedule-form').onsubmit=e=>{e.preventDefault();saveCarry(t);};}
function editModal(t=null){modal(`${modalHeader(t?'Editar tarea':'Un nuevo bloque')}<form id="task-form"><label for="task-title">Tarea</label><input id="task-title" maxlength="200" required value="${esc(t?.title||'')}" placeholder="¿A qué quieres dedicar este rato?"><div class="two-col"><div><label for="task-day">Día</label><input id="task-day" type="date" value="${t?dateKey(new Date(t.starts_at)):state.date}" required></div><div><label for="task-category">Área</label><select id="task-category">${Object.entries(CATEGORIES).map(([k,v])=>`<option value="${k}" ${t?.category===k?'selected':''}>${v}</option>`).join('')}</select></div><div><label for="task-start">Empieza</label><input id="task-start" type="time" required value="${t?timeLabel(t.starts_at):'09:00'}"></div><div><label for="task-end">Termina</label><input id="task-end" type="time" required value="${t?timeLabel(t.ends_at):'09:30'}"></div></div><label for="task-priority">Prioridad</label><select id="task-priority">${['alta','media','baja'].map(p=>`<option value="${p}" ${t?.priority===p||!t&&p==='media'?'selected':''}>${p[0].toUpperCase()+p.slice(1)}</option>`).join('')}</select><label class="checkline"><input id="task-recurring" type="checkbox" ${t?.recurrence==='daily'?'checked':''}> Repetir cada día</label><label for="task-notes">Nota o resultado esperado</label><textarea id="task-notes" rows="3" maxlength="4000">${esc(t?.notes||'')}</textarea><div class="row-actions">${btn('save-task','Guardar tarea','check','primary','type="submit"')}</div><p id="task-error" class="form-error" role="alert"></p></form>`);$('task-form').onsubmit=e=>{e.preventDefault();saveTask(t);};}
async function saveTask(t){try{const day=$('task-day').value;const item=parsePlan(JSON.stringify([{start:$('task-start').value,end:$('task-end').value,title:$('task-title').value,category:$('task-category').value,priority:$('task-priority').value,notes:$('task-notes').value,recurrence:$('task-recurring').checked?'daily':'none'}]),day)[0];await mutation(async()=>{await rpc('ritmo_save_task',{task_id:t?.id||null,item});toast('Tarea guardada.');});}catch(error){$('task-error').textContent=errorMessage(error);}}
function timeEnd(start,minutes){return new Date(new Date(start).getTime()+minutes*60000).toISOString();}
async function saveCarry(t){const start=madridTime($('carry-day').value,$('carry-time').value),end=timeEnd(start,Number($('carry-duration').value));await mutation(async()=>{await rpc('ritmo_reschedule_task',{task_id:t.id,new_start:start,new_end:end});toast('Nuevo bloque guardado.');});}
async function saveReview(){const r=reviewState,review=$('review-note').value;let start=null,end=null;if(r.mode==='postponed'){if(!$('review-day').value||!$('review-time').value){toast('Elige día y hora para el nuevo bloque.');return;}start=madridTime($('review-day').value,$('review-time').value);end=timeEnd(start,duration(r.task));}await mutation(async()=>{await rpc('ritmo_close_task',{task_id:r.task.id,outcome:r.mode,review_text:review,score:r.rating,new_start:start,new_end:end});toast(r.mode==='completed'?'Un bloque completado. Bien hecho.':'Decisión guardada. Puedes dar el siguiente paso.');});}
let planPreview;
function previewPlan(){try{const day=$('plan-date').value;if(!day)throw new Error('Elige el día del plan.');planPreview={day,tasks:parsePlan($('plan-text').value,day)};const existing=state.tasks.filter(t=>dateKey(new Date(t.starts_at))===day);if(existing.some(t=>t.status!=='pending'))throw new Error('Este día ya tiene bloques empezados o revisados. Edítalos desde la agenda para conservar su registro.');modal(`${modalHeader('Así queda tu día')}<p class="modal-detail">${esc(dayLabel(day))} · ${planPreview.tasks.length} bloques</p>${existing.length?'<div class="notice">Este plan sustituirá las tareas pendientes de este día. Los demás días se conservan.</div>':''}<div class="preview-list">${planPreview.tasks.map(t=>`<div class="preview-item"><strong>${timeLabel(t.starts_at)}–${timeLabel(t.ends_at)}</strong><span>${esc(t.title)}<br><small class="muted">${CATEGORIES[t.category]} · ${t.priority}</small></span></div>`).join('')}</div><div class="row-actions">${btn('save-plan','Guardar este plan','check','primary')}${btn('close-modal','Volver a editar')}</div>`);}catch(error){$('plan-error').textContent=errorMessage(error);}}
function base64Bytes(str){return Uint8Array.from(atob(str.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-str.length%4)%4)),c=>c.charCodeAt(0));}
async function enablePush(){
  if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window)){toast('Instala Ritmo en la pantalla de inicio y ábrela desde su icono para activar avisos.');return;}
  if(!config.vapidPublicKey){toast('Los avisos aún necesitan completar su configuración.');return;}
  try{const permission=await Notification.requestPermission();if(permission!=='granted'){toast('Activa el permiso de notificaciones en los ajustes del móvil.');return;}serviceWorker=await navigator.serviceWorker.ready;let sub=await serviceWorker.pushManager.getSubscription();if(!sub)sub=await serviceWorker.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64Bytes(config.vapidPublicKey)});
    const {error}=await db.from('ritmo_push_subscriptions').upsert({user_id:state.user.id,endpoint:sub.endpoint,subscription:sub.toJSON(),device_label:navigator.userAgent.slice(0,200)},{onConflict:'user_id,endpoint'});if(error)throw error;
    await rpc('ritmo_set_notifications',{enabled:true});toast('Avisos activados. Envía una prueba para comprobarlos.');await load();
  }catch(error){toast(errorMessage(error));}
}
async function testPush(){try{serviceWorker=await navigator.serviceWorker.ready;const sub=await serviceWorker.pushManager.getSubscription();if(!sub){toast('Activa primero los avisos en este dispositivo.');return;}const {error}=await db.functions.invoke('ritmo-push',{body:{action:'test',endpoint:sub.endpoint}});if(error)throw error;toast('Prueba enviada. Comprueba las notificaciones del móvil.');}catch(error){toast(errorMessage(error));}}
async function install(){if(installPrompt){await installPrompt.prompt();installPrompt=null;return;}modal(`${modalHeader('Lleva Ritmo contigo')}<p class="modal-detail"><strong>En iPhone</strong><br>Abre esta dirección en Safari. Pulsa Compartir y «Añadir a pantalla de inicio». Abre la app desde el nuevo icono y activa los avisos en Ajustes.</p><p class="modal-detail"><strong>En Android</strong><br>Abre esta dirección en Chrome. En el menú pulsa «Instalar aplicación» o «Añadir a pantalla de inicio». Después permite las notificaciones.</p><div class="notice">La primera vez tendrás que iniciar sesión. La sesión se mantiene en este dispositivo hasta que la cierres.</div>${btn('close-modal','Entendido','','primary')}`);}
async function copySummary(){const dayTasks=todayTasks(),carry=carryTasks().filter(t=>dateKey(new Date(t.starts_at))!==state.date);const text=summaryText(dayTasks,state.date)+(carry.length?'\n\nPendientes de días anteriores:\n'+carry.map(t=>`- ${t.title} [${STATUS[t.status]}] · ${duration(t)} min · ${t.review||t.notes||''}`).join('\n'):'');try{await navigator.clipboard.writeText(text);toast('Resumen copiado. Pégalo en nuestro chat y añade tus nuevas tareas.');}catch{modal(`${modalHeader('Tu resumen para el chat')}<textarea id="summary-copy" rows="14">${esc(text)}</textarea><p class="intro">Selecciona el texto y cópialo.</p>`);$('summary-copy').select();}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,t=getTask(b.dataset.id);if(b.type==='submit'&&['login','save-task','save-carry'].includes(action))return;try{switch(action){
case 'reset-login':renderLogin();break;
case 'navigate':state.view=b.dataset.view;state.error=null;render();window.scrollTo(0,0);break;
case 'filter':state.filter=b.dataset.filter;render();break;
case 'previous-day':state.date=addDays(state.date,-1);render();break;
case 'next-day':state.date=addDays(state.date);render();break;
case 'refresh':await load();break;
case 'close-modal':closeModal();break;
case 'start':await startTask(t);break;
case 'detail':detailModal(t);break;
case 'review':reviewModal(t,b.dataset.mode||'completed');break;
case 'review-mode':reviewState.mode=b.dataset.mode;document.querySelectorAll('.review-options button').forEach(el=>el.classList.toggle('active',el.dataset.mode===reviewState.mode));$('review-schedule').innerHTML=reviewSchedule();break;
case 'rate':reviewState.rating=Number(b.dataset.rating);document.querySelectorAll('.rating-row button').forEach(el=>el.classList.toggle('active',Number(el.dataset.rating)===reviewState.rating));break;
case 'save-review':await saveReview();break;
case 'schedule-carry':scheduleModal(t);break;
case 'new-task':editModal();break;
case 'edit-task':editModal(t);break;
case 'copy-summary':await copySummary();break;
case 'preview-plan':previewPlan();break;
case 'save-plan':await mutation(async()=>{await rpc('ritmo_import_plan',{plan_day:planPreview.day,items:planPreview.tasks});state.date=planPreview.day;state.view='today';toast('Tu plan está guardado. Un paso a la vez.');});break;
case 'copy-routine':await mutation(async()=>{const count=await rpc('ritmo_copy_routine',{from_day:state.date,to_day:addDays(state.date)});toast(`${count} tareas diarias copiadas. Las coincidencias o solapamientos se han conservado.`);});break;
case 'enable-push':b.disabled=true;await enablePush();if(b.isConnected)b.disabled=false;break;
case 'test-push':b.disabled=true;await testPush();if(b.isConnected)b.disabled=false;break;
case 'disable-push':await mutation(async()=>{await rpc('ritmo_set_notifications',{enabled:false});toast('Recordatorios pausados en todos tus dispositivos.');});break;
case 'install':await install();break;
case 'logout':await db.auth.signOut({scope:'local'});state.user=null;state.tasks=[];state.health=null;renderLogin();break;
case 'magic-link':{const email=$('email').value.trim();if(!email||!$('email').checkValidity()){toast('Escribe primero tu correo electrónico.');$('email').focus();break;}b.disabled=true;const {error}=await db.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:new URL('./',location.href).href}});if(error)throw error;toast('Enlace reenviado. Revisa tu correo.');b.disabled=false;break;}
case 'export-data':{const blob=new Blob([JSON.stringify({exported_at:new Date().toISOString(),timezone:config.timezone,tasks:state.tasks},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ritmo-${state.date}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break;}
}}catch(error){toast(errorMessage(error));if(b.isConnected)b.disabled=false;}});
document.addEventListener('change',e=>{if(e.target.id==='agenda-date'&&e.target.value){state.date=e.target.value;render();}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
window.addEventListener('online',()=>{if(state.user)load();});window.addEventListener('offline',()=>render());
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.user&&!$('modal').open)load();});
$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const rect=$('modal').getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)closeModal();}});
async function init(){
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(r=>serviceWorker=r).catch(()=>{});
  if(!config.supabaseUrl||!config.supabaseKey){$('app').innerHTML='<div class="boot"><span class="brand-icon">r.</span><h2>Tu espacio está casi listo</h2><p>Falta conectar tu cuenta. Conserva esta página y vuelve cuando termine la configuración.</p></div>';return;}
  for(let i=0;i<50&&!window.supabase;i++)await new Promise(r=>setTimeout(r,100));
  if(!window.supabase){$('app').innerHTML='<div class="boot"><h2>No se pudo abrir tu agenda</h2><p>Comprueba tu conexión y vuelve a cargar la página.</p></div>';return;}
  db=window.supabase.createClient(config.supabaseUrl,config.supabaseKey);
  db.auth.onAuthStateChange((event,session)=>{const changed=state.user?.id!==session?.user?.id;state.user=session?.user||null;if(changed){if(state.user){state.loading=true;render();setTimeout(()=>load(true),0);}else{state.tasks=[];renderLogin();}}});
  const {data:{session},error}=await db.auth.getSession();if(error)toast(errorMessage(error));state.user=session?.user||null;if(state.user)await load(true);else renderLogin();
  refreshTimer=setInterval(()=>{if(state.user&&!document.hidden&&!state.busy&&!$('modal').open&&!document.querySelector('#plan-text:focus, #plan-date:focus')&&state.view!=='planning')load();},45000);
  clockTimer=setInterval(()=>{if(state.user&&state.view==='today'&&!$('modal').open&&!state.busy){const active=document.activeElement;if(active?.tagName!=='INPUT')render();}},60000);
}
init();
